// Demo showing PERFECTLY aligned vertical lines across all rows

fn main() {
    println!("╔══════════════════════════════════════════════════════════════════════════════╗");
    println!("║                                                                              ║");
    println!("║   █████╗ ██████╗  █████╗ ██████╗ ████████╗███████╗██████╗  ██████╗ ███████╗║");
    println!("║  ██╔══██╗██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔═══██╗██╔════╝║");
    println!("║  ███████║██║  ██║███████║██████╔╝   ██║   █████╗  ██████╔╝██║   ██║███████╗║");
    println!("║  ██╔══██║██║  ██║██╔══██║██╔═══╝    ██║   ██╔══╝  ██╔══██╗██║   ██║╚════██║║");
    println!("║  ██║  ██║██████╔╝██║  ██║██║        ██║   ███████╗██║  ██║╚██████╔╝███████║║");
    println!("║  ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝        ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝║");
    println!("║                                                                              ║");
    println!("║                      SUPERBACKEND CONTROL SYSTEM                            ║");
    println!("║                                                                              ║");
    println!("╚══════════════════════════════════════════════════════════════════════════════╝");
    println!();
    println!("STATUS BAR WITH PERFECT ALIGNMENT:");
    println!("╔══════════════════════════════════════════════════╦═══════════════════════════╗");
    println!("║ Model: llama-7b-lora-q15      │ Status: [OK]     ║ ▣ LIVE │ Mem:  33% │ Q: 2 ║");
    println!("║                               │ Mode: DEV        ║  ⟳ 1s  │ TPS: 842  │      ║");
    println!("╚══════════════════════════════════════════════════╩═══════════════════════════╝");
    println!();
    println!("Note the vertical bars │ align PERFECTLY between rows!");
    println!();
    println!("SYSTEM STATUS WITH ALIGNED COLUMNS:");
    println!("╔══════════════════════════════════════════════════════════════════════════════╗");
    println!("║ [OK] Database        │ Connected    │ Latency: 1.2ms                        ║");
    println!("║ [OK] Router          │ Ready        │ Adapters: 12/50                       ║");
    println!("║ [!!] Security        │ DEVELOPMENT  │ Relaxed policies                      ║");
    println!("╠══════════════════════════════════════════════════════════════════════════════╣");
    println!("║ Services: 2 running, 4 stopped, 0 failed                                    ║");
    println!("║ Memory Headroom: 15.0% [Good >= 15%]                                        ║");
    println!("╚══════════════════════════════════════════════════════════════════════════════╝");
    println!();
    println!("SERVICE TABLE WITH PERFECT COLUMNS:");
    println!("╔══════════════════════════════════════════════════════════════════════════════╗");
    println!("║     Status  Service              State      Dependencies      Action        ║");
    println!("║    ──────────────────────────────────────────────────────────────────        ║");
    println!("║  >  [OK]    Database              Running    None              [Restart]    ║");
    println!("║     [OK]    Router                Running    Database          [Restart]    ║");
    println!("║     [--]    Metrics System        Stopped    None              [Start]      ║");
    println!("║     [--]    Policy Engine         Stopped    Router            [Start]      ║");
    println!("║     [--]    Training Service      Stopped    Database,Router   [Start]      ║");
    println!("║     [--]    Telemetry             Stopped    Metrics           [Start]      ║");
    println!("╚══════════════════════════════════════════════════════════════════════════════╝");
    println!();
    println!("MAIN MENU WITH ALIGNED COLUMNS:");
    println!("╔══════════════════════════════════════════════════════════════════════════════╗");
    println!("║  > Boot All Services          [Ready to boot]                               ║");
    println!("║    Boot Single Service        [Select from list]                            ║");
    println!("║    Debug Service              [All services healthy]                        ║");
    println!("║    Review Health              [No warnings]                                 ║");
    println!("║    View Logs                  [0 new entries]                               ║");
    println!("║    Edit Settings              [All valid]                                   ║");
    println!("║    Toggle Production Mode     [Currently: DEV]                              ║");
    println!("╚══════════════════════════════════════════════════════════════════════════════╝");
    println!();
    println!("Every vertical line │ aligns perfectly across all rows!");
    println!("Every column has fixed width for perfect alignment!");
}
