//! Report generation for verification results

use super::{CheckStatus, VerificationReport};
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn generate(report: &VerificationReport, artifacts_dir: &Path) -> Result<()> {
    // Ensure artifacts directory exists
    fs::create_dir_all(artifacts_dir)?;

    // Generate JSON report
    let json_path = artifacts_dir.join("verification_report.json");
    let json = serde_json::to_string_pretty(report)?;
    fs::write(&json_path, json)?;
    println!("  JSON report: {}", json_path.display());

    // Generate Markdown report
    let md_path = artifacts_dir.join("verification_report.md");
    let md = generate_markdown(report)?;
    fs::write(&md_path, md)?;
    println!("  Markdown report: {}", md_path.display());

    Ok(())
}

fn generate_markdown(report: &VerificationReport) -> Result<String> {
    let mut md = String::new();

    // Header
    md.push_str("# AdapterOS Agent Verification Report\n\n");
    md.push_str(&format!("**Generated:** {}\n\n", report.timestamp));

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str("| Status | Count |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!("| ✅ PASS | {} |\n", report.summary.pass));
    md.push_str(&format!("| ❌ FAIL | {} |\n", report.summary.fail));
    md.push_str(&format!("| ⏭️  SKIP | {} |\n\n", report.summary.skip));

    // Overall result
    if report.summary.fail > 0 {
        md.push_str("**Overall Result:** ❌ FAILED\n\n");
    } else if report.summary.pass > 0 {
        md.push_str("**Overall Result:** ✅ PASSED\n\n");
    } else {
        md.push_str("**Overall Result:** ⏭️  ALL SKIPPED\n\n");
    }

    // Sections
    for section in &report.sections {
        md.push_str(&format!("## {}\n\n", section.name));

        // Count section results
        let pass = section.checks.iter().filter(|c| c.status == CheckStatus::Pass).count();
        let fail = section.checks.iter().filter(|c| c.status == CheckStatus::Fail).count();
        let skip = section.checks.iter().filter(|c| c.status == CheckStatus::Skip).count();

        md.push_str(&format!(
            "**Section Summary:** {} PASS, {} FAIL, {} SKIP\n\n",
            pass, fail, skip
        ));

        // Table
        md.push_str("| Check | Status | Notes |\n");
        md.push_str("|-------|--------|-------|\n");

        for check in &section.checks {
            let status_icon = match check.status {
                CheckStatus::Pass => "✅",
                CheckStatus::Fail => "❌",
                CheckStatus::Skip => "⏭️",
            };

            let notes = if check.notes.is_empty() {
                "-".to_string()
            } else {
                check.notes.replace('\n', " ")
            };

            md.push_str(&format!(
                "| {} | {} | {} |\n",
                check.name,
                status_icon,
                notes
            ));
        }

        md.push_str("\n");

        // Details for failed checks
        let failed_checks: Vec<_> = section.checks
            .iter()
            .filter(|c| c.status == CheckStatus::Fail)
            .collect();

        if !failed_checks.is_empty() {
            md.push_str("### Failed Checks Details\n\n");
            for check in failed_checks {
                md.push_str(&format!("#### {}\n\n", check.name));
                md.push_str(&format!("**Notes:** {}\n\n", check.notes));
                if !check.evidence.is_empty() {
                    md.push_str("**Evidence:**\n\n");
                    for evidence in &check.evidence {
                        md.push_str(&format!("- {}\n", evidence));
                    }
                    md.push_str("\n");
                }
            }
        }
    }

    // Artifacts
    if !report.artifacts.is_empty() {
        md.push_str("## Artifacts\n\n");
        md.push_str("| Name | Path |\n");
        md.push_str("|------|------|\n");
        for (name, path) in &report.artifacts {
            md.push_str(&format!("| {} | `{}` |\n", name, path));
        }
        md.push_str("\n");
    }

    // Footer
    md.push_str("---\n\n");
    md.push_str("*Generated by `cargo xtask verify-agents`*\n");

    Ok(md)
}
