import React from 'react';

import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator } from '@/components/ui/breadcrumb';
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { cn } from '@/components/ui/utils';
import { Link, useLocation } from 'react-router-dom';
import { useResize } from '@/layout/LayoutProvider';

type BreadcrumbDefinition = {
  label: string;
  href?: string;
};

type ContentPadding = 'default' | 'compact' | 'none';
type MaxWidth = 'md' | 'lg' | 'xl' | 'full';

interface FeatureLayoutProps {
  title: string;
  description?: string;
  children?: React.ReactNode;

  /**
   * Override autogenerated breadcrumbs. Pass an empty array to hide them entirely.
   */
  breadcrumbs?: BreadcrumbDefinition[];
  /**
   * Additional controls rendered to the right side of the header (buttons, filters, etc.).
   */
  headerActions?: React.ReactNode;
  /**
   * Adjust outer padding tokens (defaults to `default` spacing).
   */
  contentPadding?: ContentPadding;
  /**
   * Set the max width for the content area.
   */
  maxWidth?: MaxWidth;
  /**
   * Enable resizable split panes. When true, panel sizes persist via `storageKey`.
   */
  resizable?: boolean;
  storageKey?: string;
  /**
   * Optional left panel content (appears before the primary children).
   */
  left?: React.ReactNode;
  /**
   * Optional right panel content (appears after the primary children).
   */
  right?: React.ReactNode;
  /**
   * Default panel layout percentages. If not supplied, panes split evenly.
   */
  defaultLayout?: number[];
}

const paddingClassMap: Record<ContentPadding, string> = {
  default: 'px-4 py-6 sm:p-[var(--space-6)]',
  compact: 'px-4 py-4 sm:p-[var(--space-4)]',
  none: 'p-0',
};

const maxWidthClassMap: Record<MaxWidth, string> = {
  md: 'max-w-4xl',
  lg: 'max-w-5xl',
  xl: 'max-w-[1440px]',
  full: 'max-w-none',
};

const routeLabels: Record<string, string> = {
  dashboard: 'Dashboard',
  workflow: 'Getting Started',
  trainer: 'Single-File Trainer',
  training: 'Training Jobs',
  testing: 'Testing',
  golden: 'Golden Runs',
  promotion: 'Promotion',
  adapters: 'Adapters',
  metrics: 'Metrics',
  monitoring: 'System Health',
  routing: 'Routing Inspector',
  inference: 'Inference',
  telemetry: 'Telemetry',
  replay: 'Replay',
  policies: 'Policies',
  audit: 'Audit',
  admin: 'IT Admin',
  reports: 'Reports',
  tenants: 'Tenants',
  observability: 'Observability',
};

export default function FeatureLayout({
  title,
  description,
  children,
  breadcrumbs,
  headerActions,
  contentPadding = 'default',
  maxWidth = 'xl',
  resizable,
  storageKey,
  left,
  right,
  defaultLayout,
}: FeatureLayoutProps) {
  const location = useLocation();

  const autoBreadcrumbs = React.useMemo(() => {
    const pathnames = location.pathname.split('/').filter(Boolean);
    return pathnames.map((segment, index) => ({
      href: '/' + pathnames.slice(0, index + 1).join('/'),
      label: routeLabels[segment] || segment.charAt(0).toUpperCase() + segment.slice(1).replace('-', ' '),
    }));
  }, [location.pathname]);

  const effectiveBreadcrumbs = React.useMemo(() => {
    if (breadcrumbs) {
      return breadcrumbs;
    }
    return autoBreadcrumbs;
  }, [autoBreadcrumbs, breadcrumbs]);

  const shouldRenderBreadcrumbs = effectiveBreadcrumbs.length > 0;

  const hasSplitPanels = Boolean(left) || Boolean(right);
  const panelDefinitions = React.useMemo(() => {
    const panels: Array<{ id: string; node: React.ReactNode }> = [];
    if (left) panels.push({ id: 'left', node: left });
    panels.push({ id: 'main', node: children });
    if (right) panels.push({ id: 'right', node: right });
    return panels;
  }, [children, left, right]);

  let resize: ReturnType<typeof useResize> | undefined;
  try {
    resize = useResize();
  } catch {
    resize = undefined;
  }

  const persistedLayout = React.useMemo(() => {
    if (!storageKey || !resize) return undefined;
    const saved = resize.getLayout(storageKey);
    return Array.isArray(saved) ? saved : undefined;
  }, [resize, storageKey]);

  const defaultSplit = React.useMemo(() => {
    if (defaultLayout && defaultLayout.length === panelDefinitions.length) {
      return defaultLayout;
    }
    if (panelDefinitions.length > 0) {
      const even = 100 / panelDefinitions.length;
      return panelDefinitions.map(() => even);
    }
    return undefined;
  }, [defaultLayout, panelDefinitions]);

  const [layout, setLayoutState] = React.useState<number[] | undefined>(() => {
    if (persistedLayout && persistedLayout.length === panelDefinitions.length) {
      return persistedLayout;
    }
    return defaultSplit;
  });

  React.useEffect(() => {
    if (!panelDefinitions.length) {
      setLayoutState(undefined);
      return;
    }
    if (layout && layout.length === panelDefinitions.length) {
      return;
    }
    if (persistedLayout && persistedLayout.length === panelDefinitions.length) {
      setLayoutState(persistedLayout);
      return;
    }
    if (defaultSplit) {
      setLayoutState(defaultSplit);
    }
  }, [defaultSplit, layout, panelDefinitions.length, persistedLayout]);

  const handleLayoutChange = React.useCallback(
    (sizes: number[]) => {
      if (!resizable) return;
      setLayoutState(sizes);
      if (storageKey && resize) {
        resize.setLayout(storageKey, sizes);
      }
    },
    [resizable, resize, storageKey],
  );

  const renderPanels = () => {
    if (!hasSplitPanels) {
      return children;
    }

    const panels = panelDefinitions;
    if (!panels.length) return null;

    const layoutToApply = layout ?? defaultSplit;
    return (
      <ResizablePanelGroup
        direction="horizontal"
        className="rounded-lg border border-border bg-card shadow-sm"
        onLayout={resizable ? handleLayoutChange : undefined}
      >
        {panels.map((panel, index) => (
          <React.Fragment key={panel.id}>
            <ResizablePanel defaultSize={layoutToApply?.[index]} className="flex min-h-0 flex-col">
              <div className="min-h-0 flex-1 overflow-auto p-[var(--space-4)]">{panel.node}</div>
            </ResizablePanel>
            {index < panels.length - 1 && <ResizableHandle withHandle={Boolean(resizable)} />}
          </React.Fragment>
        ))}
      </ResizablePanelGroup>
    );
  };

  return (
    <div className={cn('min-h-0 min-w-0', paddingClassMap[contentPadding])}>
      <div className={cn('mx-auto', maxWidthClassMap[maxWidth])}>
        <header className="mb-[var(--section-gap)]">
          <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
            <div>
              <h1 className="[font-size:var(--font-h1)] font-bold text-[var(--gray-900)]">{title}</h1>
              {description && (
                <p className="[font-size:var(--font-body)] text-[var(--gray-600)] mt-[var(--space-2)]">{description}</p>
              )}
            </div>
            {headerActions && <div className="flex items-center gap-2 self-start md:self-auto">{headerActions}</div>}
          </div>
          {shouldRenderBreadcrumbs && (
            <Breadcrumb className="mt-3 hidden sm:flex">
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link to="/">Home</Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              {effectiveBreadcrumbs.map((crumb, index) => {
                const isLast = index === effectiveBreadcrumbs.length - 1;
                return (
                  <React.Fragment key={`${crumb.label}-${index}`}>
                    <BreadcrumbSeparator />
                    <BreadcrumbItem>
                      {crumb.href && !isLast ? (
                        <BreadcrumbLink asChild>
                          <Link to={crumb.href}>{crumb.label}</Link>
                        </BreadcrumbLink>
                      ) : (
                        <span aria-current={isLast ? 'page' : undefined} className="text-sm text-muted-foreground">
                          {crumb.label}
                        </span>
                      )}
                    </BreadcrumbItem>
                  </React.Fragment>
                );
              })}
            </Breadcrumb>
          )}
        </header>

        <main
          className={cn(
            'grid gap-[var(--space-4)] border-t border-[var(--gray-300)] pt-[var(--space-6)]',
            hasSplitPanels ? 'min-h-[480px]' : undefined,
          )}
        >
          {renderPanels()}
        </main>
      </div>
    </div>
  );
}
