import React from 'react';
import { useLocation } from 'react-router-dom';

import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { cn } from '@/components/ui/utils';
import { useResize } from '@/providers/CoreProviders';
import { PageHeader, PageHeaderAction, PageHeaderBadge } from '@/components/ui/page-header';
import { logger } from '@/utils/logger';
import { formatClusterPrefixedLabel } from '@/config/routes';

type BreadcrumbDefinition = {
  label: string;
  href?: string;
};

type ContentPadding = 'default' | 'compact' | 'none';
type MaxWidth = 'md' | 'lg' | 'xl' | 'full';

interface FeatureLayoutProps {
  title: string;
  description?: string;
  children?: React.ReactNode;
  customHeader?: React.ReactNode;

  /**
   * Override autogenerated breadcrumbs. Pass an empty array to hide them entirely.
   */
  breadcrumbs?: BreadcrumbDefinition[];
  /**
   * Additional controls rendered to the right side of the header (buttons, filters, etc.).
   * @deprecated Use primaryAction and secondaryActions instead
   */
  headerActions?: React.ReactNode;
  /**
   * Primary action button for the page header
   */
  primaryAction?: PageHeaderAction;
  /**
   * Secondary action buttons for the page header
   */
  secondaryActions?: PageHeaderAction[];
  /**
   * Badges to display in the page header
   */
  badges?: PageHeaderBadge[];
  /**
   * Glossary term ID for the page header tooltip
   */
  termId?: string;
  /**
   * Brief tooltip content for the page header
   */
  brief?: string;
  /**
   * Adjust outer padding tokens (defaults to `default` spacing).
   */
  contentPadding?: ContentPadding;
  /**
   * Set the max width for the content area.
   */
  maxWidth?: MaxWidth;
  /**
   * Enable resizable split panes. When true, panel sizes persist via `storageKey`.
   */
  resizable?: boolean;
  storageKey?: string;
  /**
   * Optional left panel content (appears before the primary children).
   */
  left?: React.ReactNode;
  /**
   * Optional right panel content (appears after the primary children).
   */
  right?: React.ReactNode;
  /**
   * Default panel layout percentages. If not supplied, panes split evenly.
   */
  defaultLayout?: number[];
}

const paddingClassMap: Record<ContentPadding, string> = {
  default: 'px-[var(--space-4)] py-[var(--space-6)] sm:p-[var(--space-6)]',
  compact: 'px-[var(--space-4)] py-[var(--space-4)] sm:p-[var(--space-4)]',
  none: 'p-0',
};

const maxWidthClassMap: Record<MaxWidth, string> = {
  md: 'max-w-[var(--layout-content-width-md)]',
  lg: 'max-w-[var(--layout-content-width-lg)]',
  xl: 'max-w-[var(--layout-content-width-xl)]',
  full: 'max-w-none',
};

export default function FeatureLayout({
  title,
  description,
  children,
  breadcrumbs,
  headerActions,
  primaryAction,
  secondaryActions,
  badges,
  termId,
  brief,
  contentPadding = 'default',
  maxWidth = 'xl',
  resizable,
  storageKey,
  left,
  right,
  defaultLayout,
  customHeader,
}: FeatureLayoutProps) {
  const location = useLocation();
  // IA rule: page headers must be prefixed with the owning cluster
  const prefixedTitle = formatClusterPrefixedLabel(location.pathname, title, ' / ');

  // Note: breadcrumbs are now rendered in the global header (AppHeader)
  // The breadcrumbs prop is kept for backward compatibility but no longer rendered here

  const hasSplitPanels = Boolean(left) || Boolean(right);
  const panelDefinitions = React.useMemo(() => {
    const panels: Array<{ id: string; node: React.ReactNode }> = [];
    if (left) panels.push({ id: 'left', node: left });
    panels.push({ id: 'main', node: children });
    if (right) panels.push({ id: 'right', node: right });
    return panels;
  }, [children, left, right]);

  let resize: ReturnType<typeof useResize> | undefined;
  try {
    resize = useResize();
  } catch {
    resize = undefined;
  }

  const persistedLayout = React.useMemo(() => {
    if (!storageKey || !resize) return undefined;
    const saved = resize.getLayout(storageKey);
    return Array.isArray(saved) ? saved : undefined;
  }, [resize, storageKey]);

  const defaultSplit = React.useMemo(() => {
    if (defaultLayout && defaultLayout.length === panelDefinitions.length) {
      return defaultLayout;
    }
    if (panelDefinitions.length > 0) {
      const even = 100 / panelDefinitions.length;
      return panelDefinitions.map(() => even);
    }
    return undefined;
  }, [defaultLayout, panelDefinitions]);

  const [layout, setLayoutState] = React.useState<number[] | undefined>(() => {
    if (persistedLayout && persistedLayout.length === panelDefinitions.length) {
      return persistedLayout;
    }
    return defaultSplit;
  });

  React.useEffect(() => {
    if (!panelDefinitions.length) {
      setLayoutState(undefined);
      return;
    }
    if (layout && layout.length === panelDefinitions.length) {
      return;
    }
    if (persistedLayout && persistedLayout.length === panelDefinitions.length) {
      setLayoutState(persistedLayout);
      return;
    }
    if (defaultSplit) {
      setLayoutState(defaultSplit);
    }
  }, [defaultSplit, layout, panelDefinitions.length, persistedLayout]);

  const handleLayoutChange = React.useCallback(
    (sizes: number[]) => {
      if (!resizable) return;
      setLayoutState(sizes);
      if (storageKey && resize) {
        resize.setLayout(storageKey, sizes);
      }
    },
    [resizable, resize, storageKey],
  );

  const renderPanels = () => {
    if (!hasSplitPanels) {
      return children;
    }

    const panels = panelDefinitions;
    // Defensive fallback: if split panels enabled but array empty, render children directly
    // This prevents blank pages in edge cases where panelDefinitions might be unexpectedly empty
    if (!panels.length) {
      if (process.env.NODE_ENV === 'development') {
        logger.warn('FeatureLayout: hasSplitPanels is true but panelDefinitions is empty, falling back to children');
      }
      return children;
    }

    const layoutToApply = layout ?? defaultSplit;
    return (
      <ResizablePanelGroup
        direction="horizontal"
        className="rounded-lg border border-border bg-card shadow-sm"
        onLayout={resizable ? handleLayoutChange : undefined}
      >
        {panels.map((panel, index) => (
          <React.Fragment key={panel.id}>
            <ResizablePanel defaultSize={layoutToApply?.[index]} className="flex min-h-0 flex-col">
              <div className="min-h-0 flex-1 overflow-auto p-[var(--space-4)]">{panel.node}</div>
            </ResizablePanel>
            {index < panels.length - 1 && <ResizableHandle withHandle={Boolean(resizable)} />}
          </React.Fragment>
        ))}
      </ResizablePanelGroup>
    );
  };

  return (
    <>
      {/* Scroll strategy: outer layout stays non-scrolling; panel bodies manage their own overflow when needed. */}
      <div className={cn('min-h-0 min-w-0', paddingClassMap[contentPadding])}>
        <div className={cn('mx-auto', maxWidthClassMap[maxWidth])}>
          <header className="mb-[var(--section-gap)]">
            {customHeader ?? (
              <PageHeader
                title={prefixedTitle}
                description={description}
                primaryAction={primaryAction}
                secondaryActions={secondaryActions}
                badges={badges}
                termId={termId}
                brief={brief}
              >
                {headerActions}
              </PageHeader>
            )}
          </header>

          <main
            className={cn(
              'grid gap-[var(--space-4)] border-t border-[var(--gray-300)] pt-[var(--space-6)]',
              hasSplitPanels ? 'min-h-[calc(var(--base-unit)*120)]' : undefined,
            )}
          >
            {renderPanels()}
          </main>
        </div>
      </div>
    </>
  );
}
