//! Worker management types
//!
//! Types for worker lifecycle management, registration, and health tracking.

use serde::{Deserialize, Serialize};

use crate::schema_version;

/// Worker-specific model load state for smarter routing decisions
///
/// Enables the control plane to route requests to workers with models already loaded,
/// avoiding cold-start latency and memory pressure from concurrent model loads.
///
/// Note: This is distinct from `ModelLoadStatus` in `model_status.rs` which is used
/// for model management APIs. This type is specifically for worker runtime state.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum WorkerModelLoadState {
    /// No model currently loaded in memory
    #[default]
    Unloaded,
    /// Model is actively being loaded (weights transfer in progress)
    Loading,
    /// Model is fully loaded and ready for inference
    Loaded,
    /// Model load failed with an error message
    #[serde(rename = "error")]
    Error(String),
}

impl std::fmt::Display for WorkerModelLoadState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkerModelLoadState::Unloaded => write!(f, "unloaded"),
            WorkerModelLoadState::Loading => write!(f, "loading"),
            WorkerModelLoadState::Loaded => write!(f, "loaded"),
            WorkerModelLoadState::Error(msg) => write!(f, "error: {}", msg),
        }
    }
}

/// Worker registration request
///
/// Sent by worker on startup to register with the control plane.
/// The control plane validates manifest_hash against the plan's expected manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerRegistrationRequest {
    /// Unique worker ID (UUID v7, generated by worker)
    pub worker_id: String,
    /// Tenant this worker serves
    pub tenant_id: String,
    /// Plan ID this worker was spawned from
    pub plan_id: String,
    /// BLAKE3 hash of the loaded manifest (hex-encoded)
    pub manifest_hash: String,
    /// Backend selected by worker (e.g., mlx, metal, coreml)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Base model hash advertised by worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_hash: Option<String>,
    /// Tokenizer hash (BLAKE3 hex) loaded by the worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_hash_b3: Option<String>,
    /// Tokenizer vocabulary size observed by the worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_vocab_size: Option<u32>,
    /// Schema version (e.g., "1.0")
    pub schema_version: String,
    /// API version for CP-worker protocol (e.g., "1.0")
    pub api_version: String,
    /// Worker process ID
    pub pid: i32,
    /// Unix domain socket path for this worker
    pub uds_path: String,
    /// Backend capabilities (e.g., ["coreml", "mlx"])
    #[serde(default)]
    pub capabilities: Vec<String>,
    /// Structured worker capabilities (backend kind + supported modes)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capabilities_detail: Option<WorkerCapabilities>,
    /// Whether worker is running in strict mode (fail-closed on errors)
    #[serde(default)]
    pub strict_mode: bool,
}

/// Structured backend capabilities for worker registration and routing
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerCapabilities {
    /// Backend kind: mlx, metal, coreml, bridge
    pub backend_kind: String,
    /// Optional implementation detail (e.g., "mlx_subprocess")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub implementation: Option<String>,
    /// Supports token-by-token inference (run_step)
    pub supports_step: bool,
    /// Supports bulk text generation (generate_text_complete)
    pub supports_bulk: bool,
    /// Supports returning logits (step path)
    pub supports_logits: bool,
    /// Supports streaming tokens via step loop
    pub supports_streaming: bool,
    /// Supports GPU backward pass for training (MLX autograd).
    #[serde(default)]
    pub gpu_backward: bool,
    /// Binary compiled with multi-backend support.
    #[serde(default)]
    pub multi_backend: bool,
}

/// Worker registration response
///
/// Returned by control plane after validating registration request.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerRegistrationResponse {
    /// Whether the registration was accepted
    pub accepted: bool,
    /// Worker ID (echoed back)
    pub worker_id: String,
    /// Reason for rejection (if not accepted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    /// Heartbeat interval in seconds
    pub heartbeat_interval_secs: u32,
    /// KV cache quota in bytes (None = unlimited)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kv_quota_bytes: Option<u64>,
    /// KV residency policy ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kv_residency_policy_id: Option<String>,
    /// Whether control plane is running in strict mode (fail-closed on errors)
    /// Workers should use this to detect strict mode mismatch.
    #[serde(default)]
    pub cp_strict_mode: bool,
}

/// Manifest fetch response for workers
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerManifestFetchResponse {
    /// BLAKE3 hash of the manifest (hex-encoded)
    pub manifest_hash: String,
    /// Canonical JSON representation (hash is computed over these bytes)
    pub manifest_json: String,
    /// YAML rendering for readability
    pub manifest_yaml: String,
}

/// Worker status notification
///
/// Sent by worker to notify control plane of status changes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerStatusNotification {
    /// Worker ID
    pub worker_id: String,
    /// New status (created, registered, healthy, draining, stopped, error)
    pub status: String,
    /// Reason for the status change
    pub reason: String,
    /// Tokenizer hash (BLAKE3 hex) loaded by the worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_hash_b3: Option<String>,
    /// Tokenizer vocabulary size observed by the worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_vocab_size: Option<u32>,
    /// Current cache memory usage in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_used_mb: Option<u32>,
    /// Maximum cache memory budget in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_max_mb: Option<u32>,
    /// Number of pinned cache entries (cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_pinned_entries: Option<u32>,
    /// Number of active cache entries (in-use, cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_active_entries: Option<u32>,
    /// CoreML failure stage reported by the worker (if any)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_stage: Option<String>,
    /// CoreML failure reason reported by the worker (if any)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_reason: Option<String>,
    /// BLAKE3 hash of the currently loaded model (for routing affinity)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loaded_model_hash: Option<String>,
    /// Current model load state (unloaded, loading, loaded, error)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_load_state: Option<WorkerModelLoadState>,
    /// Total cache memory usage in bytes (more precise than cache_used_mb)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_memory_bytes: Option<u64>,
    /// Cache hit ratio (0.0 to 1.0) for performance monitoring
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_hit_ratio: Option<f32>,
}

/// Spawn worker request
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct SpawnWorkerRequest {
    pub tenant_id: String,
    pub node_id: String,
    pub plan_id: String,
    pub uds_path: String,
}

/// Worker response
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerResponse {
    #[serde(default = "schema_version")]
    pub schema_version: String,
    pub id: String,
    pub tenant_id: String,
    pub node_id: String,
    pub plan_id: String,
    pub uds_path: String,
    pub pid: Option<i32>,
    pub status: String,
    pub started_at: String,
    pub last_seen_at: Option<String>,
    /// Backend capabilities advertised by the worker
    #[serde(default)]
    pub capabilities: Vec<String>,
    /// Structured capabilities advertised by the worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capabilities_detail: Option<WorkerCapabilities>,
    /// Backend selected by the worker (e.g., mlx, metal, coreml)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Base model ID expected/loaded by this worker (from manifest)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    /// Base model hash (BLAKE3 hex) expected/loaded by this worker (from manifest/worker)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_hash: Option<String>,
    /// Tokenizer hash (BLAKE3 hex) loaded by this worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_hash_b3: Option<String>,
    /// Tokenizer vocab size loaded by this worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_vocab_size: Option<u32>,
    /// CoreML failure stage reported by the worker (if any)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_stage: Option<String>,
    /// CoreML failure reason reported by the worker (if any)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_reason: Option<String>,
    /// Whether the worker is in a state that implies the base model is loaded
    #[serde(default)]
    pub model_loaded: bool,
    /// Current cache memory usage in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_used_mb: Option<u32>,
    /// Maximum cache memory budget in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_max_mb: Option<u32>,
    /// Number of pinned cache entries (cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_pinned_entries: Option<u32>,
    /// Number of active cache entries (in-use, cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_active_entries: Option<u32>,
}

/// Worker status update
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerStatusUpdate {
    pub worker_id: String,
    pub status: String,
    pub timestamp: String,
}

/// Worker heartbeat request
///
/// Sent periodically by workers to report liveness and health.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerHeartbeatRequest {
    /// Worker ID sending the heartbeat
    pub worker_id: String,
    /// Current status (e.g., healthy, draining)
    pub status: String,
    /// Optional memory usage percentage
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_usage_pct: Option<f64>,
    /// Optional count of currently loaded adapters
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adapters_loaded: Option<u32>,
    /// ISO-8601 timestamp provided by worker
    pub timestamp: String,
    /// Current cache memory usage in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_used_mb: Option<u32>,
    /// Maximum cache memory budget in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_max_mb: Option<u32>,
    /// Number of pinned cache entries (cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_pinned_entries: Option<u32>,
    /// Number of active cache entries (in-use, cannot be evicted)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_active_entries: Option<u32>,
    /// Tokenizer hash (BLAKE3 hex) loaded by this worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_hash_b3: Option<String>,
    /// Tokenizer vocab size loaded by this worker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_vocab_size: Option<u32>,
    /// CoreML failure stage (init/config/model_path/model_integrity/runtime)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_stage: Option<String>,
    /// CoreML failure reason (stage-specific)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coreml_failure_reason: Option<String>,
}

/// Worker heartbeat response
///
/// Returned by control plane to acknowledge heartbeat and provide next interval.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub struct WorkerHeartbeatResponse {
    /// Whether the heartbeat was accepted
    pub acknowledged: bool,
    /// Recommended seconds until the next heartbeat
    pub next_heartbeat_secs: u32,
}

/// Worker metrics response
///
/// Detailed metrics for a worker instance, including memory, GPU, and performance stats.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct WorkerMetricsResponse {
    pub worker_id: String,
    /// Memory usage in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_used_mb: Option<u64>,
    /// Memory limit in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_limit_mb: Option<u64>,
    /// GPU memory used in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gpu_memory_used_mb: Option<u64>,
    /// GPU memory total in MB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gpu_memory_total_mb: Option<u64>,
    /// GPU utilization percentage
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gpu_utilization_pct: Option<f64>,
    /// CPU utilization percentage
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_utilization_pct: Option<f64>,
    /// Requests processed
    #[serde(default)]
    pub requests_processed: u64,
    /// Requests per second
    #[serde(default)]
    pub requests_per_second: f64,
    /// Average latency in ms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avg_latency_ms: Option<f64>,
    /// P99 latency in ms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub p99_latency_ms: Option<f64>,
    /// Uptime in seconds
    #[serde(default)]
    pub uptime_seconds: u64,
    /// Cache entries count
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_entries: Option<u32>,
    /// Cache hit rate
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_hit_rate: Option<f64>,
}
