//! Curated adjective word list for word alias generation.
//!
//! FROZEN: Do not modify this list after initial commit.
//! Word alias determinism depends on stable indices.

pub const ADJECTIVES: [&str; 1024] = [
    "able", "acacia", "acorn", "acute", "adept", "aerial", "agate", "aged", "agile", "airy",
    "alder", "alert", "alive", "alloy", "aloft", "alpha", "alpine", "alto", "amber", "ample",
    "anchor", "anise", "annual", "antic", "apple", "apric", "apt", "aqua", "aquatic", "arch",
    "arctic", "backed", "badge", "balmy", "bamboo", "band", "banded", "bare", "barley", "basalt",
    "basic", "basil", "bay", "beady", "beam", "beige", "belt", "bench", "bent", "berry", "bevel",
    "biome", "birch", "bland", "blaze", "bliss", "bloom", "blown", "bluff", "blunt", "bold",
    "bone", "boreal", "bound", "boxed", "brash", "brass", "brave", "brazen", "breezy", "brick",
    "brief", "bright", "cacao", "cairn", "calm", "cameo", "candy", "cape", "cargo", "carved",
    "cedar", "celery", "chalk", "chief", "chill", "china", "chive", "choral", "chord", "cipher",
    "citrus", "civic", "civil", "clad", "clam", "clang", "clank", "claret", "clasp", "clay",
    "clean", "clear", "cleft", "cliff", "close", "cloud", "clove", "clover", "coal", "coast",
    "cobalt", "cocoa", "coda", "combed", "comet", "comfy", "comic", "common", "conch", "conic",
    "cool", "coped", "copper", "coral", "cord", "core", "cored", "cornet", "daily", "daisy",
    "damp", "dandy", "dapper", "dapple", "dawn", "dear", "deep", "deft", "delta", "dense", "depot",
    "depth", "dewdrop", "dewy", "dialed", "digit", "dimly", "dimple", "dingo", "dipped", "dire",
    "direct", "dock", "domed", "done", "dorsal", "dotted", "downy", "dozen", "draft", "draped",
    "drawn", "dried", "eager", "early", "earth", "earthy", "eased", "ebon", "eddy", "edged",
    "eight", "eighth", "elder", "elfin", "elite", "elm", "ember", "emerl", "emery", "empty",
    "enamel", "endow", "entry", "epoch", "epoxy", "equal", "equine", "fable", "fabric", "faced",
    "faceted", "facto", "faded", "faint", "fair", "false", "famed", "fancy", "farmed", "fast",
    "fawn", "felt", "felted", "fennel", "fern", "ferric", "fibre", "fiery", "fifth", "filmy",
    "final", "fine", "finely", "firm", "first", "fizzy", "fjord", "flaked", "flaky", "flame",
    "flash", "flat", "flaxen", "fleece", "fleet", "flint", "flora", "floral", "fluid", "flush",
    "foam", "focal", "foggy", "folded", "folk", "fond", "forge", "gabled", "gamma", "garnet",
    "gauze", "gauzy", "gay", "geared", "gemmy", "gentle", "giant", "giddy", "gilded", "given",
    "glad", "glass", "glassy", "glaze", "glazed", "gleam", "glen", "glib", "glossy", "glow",
    "gold", "golden", "good", "gothic", "grace", "grain", "grand", "grape", "graph", "grass",
    "grassy", "gravel", "gray", "haberd", "hairy", "hale", "half", "halt", "hammer", "handy",
    "happy", "harbor", "hardy", "harp", "haste", "hazel", "heart", "heated", "heath", "heavy",
    "hedge", "hefty", "held", "helium", "hemp", "henna", "herb", "herbal", "heron", "hewn", "hex",
    "hidden", "high", "hilly", "holdup", "hollow", "homing", "honed", "iamb", "iced", "icicle",
    "ideal", "ignite", "inch", "indie", "indus", "inert", "inked", "inlaid", "inland", "inlay",
    "inner", "insert", "inter", "inward", "iodine", "ionic", "jade", "jasper", "java", "jazzy",
    "jest", "jet", "jewel", "jeweled", "jigsaw", "joined", "joint", "jolly", "jolt", "jostle",
    "joule", "jovial", "joy", "judge", "kale", "karmic", "kayak", "keen", "keenly", "kept",
    "kernel", "kettle", "key", "khaki", "kind", "kinder", "knelt", "knight", "knit", "lace",
    "lacey", "laden", "lagoon", "lake", "lamina", "lance", "lanky", "lapel", "lapis", "larch",
    "large", "laser", "latch", "late", "latest", "lathe", "latte", "laurel", "lava", "lavish",
    "lawn", "lead", "leaf", "leafy", "lean", "leapt", "ledge", "ledger", "left", "legal", "lemon",
    "lemony", "lentil", "level", "lever", "lichen", "lifer", "light", "lilac", "lilted", "lily",
    "limber", "lime", "limpid", "lined", "linen", "lining", "linseed", "lion", "listed", "lit",
    "lithe", "lithic", "litmus", "live", "livid", "loamy", "lobed", "local", "mace", "macro",
    "made", "magic", "magnet", "main", "major", "malt", "mango", "manor", "mantle", "maple",
    "mapped", "marble", "marsh", "marshy", "mason", "mastic", "matt", "matted", "mauve", "meadow",
    "mealy", "medal", "medley", "melon", "mental", "merged", "merit", "merry", "mesa", "mesh",
    "metal", "metric", "metro", "mica", "micro", "mid", "mild", "milky", "mill", "milled", "mini",
    "minor", "mint", "minty", "misty", "mitten", "mixed", "mobile", "mocha", "modal", "model",
    "mohawk", "moist", "molar", "naiad", "naive", "named", "nano", "natal", "native", "naval",
    "near", "neat", "nectar", "neon", "net", "nettle", "new", "newer", "next", "nice", "night",
    "nimble", "ninth", "noble", "nodal", "oaken", "oasis", "oat", "ocean", "ocher", "ochre",
    "octal", "odd", "offset", "olive", "omega", "onion", "onyx", "oolite", "opal", "opaline",
    "opaque", "open", "opted", "optic", "orbit", "orchid", "ore", "organ", "origin", "ornate",
    "paced", "pacific", "padded", "paddy", "paged", "paint", "paired", "pale", "palm", "palmed",
    "panel", "paper", "par", "parcel", "parity", "park", "parts", "paste", "pasted", "pastel",
    "pastry", "patch", "patchy", "path", "patron", "paved", "peach", "peak", "pearl", "pearly",
    "pebble", "pecan", "pecked", "penned", "penny", "pepper", "perch", "perky", "petal", "pewter",
    "phased", "phenom", "phial", "photo", "piano", "pickle", "picky", "pillar", "pilot", "pine",
    "pink", "pint", "piped", "pitch", "pitted", "pixel", "plaid", "plain", "plait", "plane",
    "planed", "plank", "plant", "plasma", "plate", "plated", "played", "plaza", "pleated",
    "pliant", "plied", "plowed", "plucky", "plumb", "plume", "plump", "plush", "plying", "podgy",
    "poem", "point", "polar", "polka", "polled", "poly", "pond", "ponder", "poplar", "poppy",
    "port", "quad", "quail", "quaint", "quake", "quartz", "quasi", "queen", "query", "quest",
    "quiche", "quick", "quiet", "quill", "quilt", "radar", "radial", "radio", "rafted", "rafts",
    "ragged", "rain", "raked", "rally", "ramble", "ranch", "range", "rangy", "rapid", "rare",
    "rattan", "raven", "raw", "ray", "razor", "ready", "real", "realm", "reborn", "reckon",
    "redden", "reed", "reef", "regal", "regent", "relay", "relic", "relish", "remedy", "remit",
    "renal", "renew", "rental", "reopen", "repaid", "repose", "resin", "resiny", "retail", "retro",
    "rhymed", "ribbed", "rich", "ridge", "ridged", "rifle", "right", "rigid", "rind", "rinded",
    "ringed", "rinse", "ripe", "ripple", "risen", "ritual", "river", "rivet", "road", "roamed",
    "roast", "robin", "robust", "rocky", "rodent", "rogue", "sable", "safe", "sage", "saline",
    "salt", "salty", "same", "sand", "sanded", "sandy", "sane", "sapid", "sash", "satin", "saved",
    "savor", "scale", "scene", "scenic", "scone", "scope", "scroll", "sea", "sedge", "seeded",
    "sepal", "serene", "serial", "serif", "sesame", "set", "seven", "sewn", "shade", "shaded",
    "shadow", "shale", "sham", "shanty", "shape", "shared", "sharp", "shawl", "sheen", "sheer",
    "shelf", "shell", "shield", "shift", "shine", "shiny", "shoal", "shore", "short", "shown",
    "sided", "sigma", "signal", "silica", "silk", "silky", "silo", "silver", "sine", "sinter",
    "sixth", "sized", "skate", "skein", "sketch", "skimp", "skimpy", "slate", "sleek", "sleet",
    "slice", "slim", "sloped", "slung", "small", "smart", "smoke", "smoky", "smooth", "snappy",
    "snowy", "snug", "soapy", "sober", "socle", "sodium", "soft", "solar", "sole", "solid",
    "sonic", "sorted", "sound", "south", "space", "spaced", "span", "spare", "spark", "spear",
    "spec", "spelt", "spent", "spice", "spicy", "spine", "spiral", "spoke", "spoken", "sport",
    "spray", "sprig", "sprout", "spruce", "spry", "spun", "squad", "squid", "stable", "stage",
    "stake", "stale", "star", "starch", "stark", "steady", "tabby", "table", "tabled", "taffy",
    "taken", "tale", "tall", "tally", "talon", "tame", "tan", "tandem", "tango", "tangy", "taped",
    "tart", "tassel", "taste", "tawny", "teak", "teal", "tempo", "tender", "tenor", "tent",
    "tepid", "terra", "terse", "test", "tested", "thatch", "thawed", "themed", "theta", "thick",
    "thin", "third", "thorn", "thresh", "thrift", "thrush", "ticked", "tidal", "tidy", "tied",
    "tiger", "tight", "tile", "tiled", "timber", "time", "timid", "tint", "tiny", "tipped",
    "titian", "toast", "toggle", "tonal", "tonic", "tooled", "topaz", "torch", "torque", "total",
    "totem", "tower", "trace", "traced", "track", "traded", "trail", "trait", "tray", "tree",
    "triad", "trial", "tried", "ultra", "umber", "umbral", "unaged", "unbent", "unborn",
    "uncapped", "uncut", "under", "undyed", "uneven", "unfold", "union", "unique", "unite",
    "unity", "unkempt", "unlit", "unnamed", "until", "untold", "unworn", "upbeat", "upheld",
    "vacant", "valid", "valley", "valued", "valve", "vanilla", "vapor", "varied", "vast", "vault",
    "vegan", "velvet", "verdant", "verged", "vernal", "verse", "versed", "vest", "vested", "vetch",
    "viable", "video", "viewed", "vigil", "vine", "vinyl", "viola", "violet", "wade", "wading",
    "wafer", "waffle", "waged", "walled", "walnut", "waltz", "warden", "warm", "warp", "warped",
    "washed", "watch", "water", "wattle", "waved", "wax", "waxed", "waxen", "weave", "wedge",
    "wedged", "weedy", "weld", "welded", "well", "west", "wheat", "wheel", "whiff", "while",
    "whimsy", "whirl", "white", "whole", "wick", "wicker", "wide", "wield", "wild", "willow",
    "wilt", "xeric", "yacht", "yard", "yarn", "yarned", "year", "yeast", "yellow", "yielded",
    "zeal", "zealot", "zen", "zenith", "zephyr", "zero", "zest", "zesty", "zigzag", "zinc",
];
