#!/usr/bin/env bash
# Generate route map documentation from routes.rs
#
# Usage:
#   ./scripts/docs/generate_route_map.sh > docs/engineering/ROUTE_MAP.md
#
# This script extracts:
# - Route paths from utoipa annotations
# - Handler function names
# - HTTP methods

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ROUTES_FILE="$ROOT/crates/adapteros-server-api/src/routes.rs"
HANDLERS_DIR="$ROOT/crates/adapteros-server-api/src/handlers"

echo "# adapterOS Route Map"
echo ""
echo "> Auto-generated from \`routes.rs\` and handler files."
echo "> Last updated: $(date -Idate)"
echo ""
echo "This document maps API routes to their handler implementations for developer reference."
echo ""

# Count routes
ROUTE_COUNT=$(grep -c 'path = "' "$ROUTES_FILE" 2>/dev/null || echo "0")
echo "**Total Routes:** ~$ROUTE_COUNT"
echo ""

echo "## Route Categories"
echo ""
echo "| Category | Description |"
echo "|----------|-------------|"
echo "| Auth | Authentication, login, MFA, sessions |"
echo "| Inference | Streaming and batch inference |"
echo "| Adapters | Adapter CRUD, versions, health |"
echo "| Training | Training jobs, datasets, checkpoints |"
echo "| Chat | Chat sessions, messages, evidence |"
echo "| System | Health checks, status, diagnostics |"
echo "| Admin | Tenants, workspaces, policies |"
echo ""

echo "## Handler Files"
echo ""
echo "| File | Purpose |"
echo "|------|---------|"

# List handler files
for f in "$HANDLERS_DIR"/*.rs; do
    if [[ -f "$f" ]]; then
        basename=$(basename "$f" .rs)
        # Get first doc comment or description
        desc=$(head -20 "$f" | grep -m1 '^//!' | sed 's/^\/\/! *//' || echo "Handler module")
        echo "| \`handlers/$basename.rs\` | $desc |"
    fi
done
echo ""

echo "## Handler Subdirectories"
echo ""
for d in "$HANDLERS_DIR"/*/; do
    if [[ -d "$d" ]]; then
        dirname=$(basename "$d")
        file_count=$(find "$d" -name "*.rs" | wc -l | tr -d ' ')
        echo "- \`handlers/$dirname/\` ($file_count files)"
    fi
done
echo ""

echo "## Route → Handler Mapping"
echo ""
echo "### Authentication Routes"
echo ""
echo "| Method | Path | Handler |"
echo "|--------|------|---------|"
grep -E 'path = "/api/v1/auth' "$ROUTES_FILE" | head -20 | while read -r line; do
    path=$(echo "$line" | sed 's/.*path = "\([^"]*\)".*/\1/')
    echo "| - | \`$path\` | See handlers/auth*.rs |"
done
echo ""

echo "### Inference Routes"
echo ""
echo "| Method | Path | Handler |"
echo "|--------|------|---------|"
grep -E 'path = "/api/v1/infer' "$ROUTES_FILE" | head -10 | while read -r line; do
    path=$(echo "$line" | sed 's/.*path = "\([^"]*\)".*/\1/')
    echo "| POST | \`$path\` | See handlers/streaming_infer.rs |"
done
echo ""

echo "### Adapter Routes"
echo ""
echo "| Method | Path | Handler |"
echo "|--------|------|---------|"
grep -E 'path = "/api/v1/adapters' "$ROUTES_FILE" | head -15 | while read -r line; do
    path=$(echo "$line" | sed 's/.*path = "\([^"]*\)".*/\1/')
    echo "| - | \`$path\` | See handlers/adapters/ |"
done
echo ""

echo "### System Routes"
echo ""
echo "| Method | Path | Handler |"
echo "|--------|------|---------|"
echo "| GET | \`/healthz\` | handlers/health.rs |"
echo "| GET | \`/readyz\` | handlers/health.rs |"
echo "| GET | \`/api/system/ready\` | handlers/system_status.rs |"
echo ""

echo "## Key Files Reference"
echo ""
echo "| File | Lines | Description |"
echo "|------|-------|-------------|"
echo "| \`routes.rs\` | $(wc -l < "$ROUTES_FILE" | tr -d ' ') | OpenAPI route registration |"
echo "| \`handlers.rs\` | $(wc -l < "$HANDLERS_DIR.rs" 2>/dev/null || echo "?") | Handler module exports |"
echo "| \`middleware/mod.rs\` | $(wc -l < "$ROOT/crates/adapteros-server-api/src/middleware/mod.rs" 2>/dev/null || echo "?") | Middleware stack |"
echo ""

echo "## Change Dependencies"
echo ""
echo "When modifying routes:"
echo ""
echo "1. **Adding a new route:**"
echo "   - Add handler in \`handlers/*.rs\`"
echo "   - Register in \`handlers.rs\` (pub mod)"
echo "   - Add path to \`routes.rs\` \`#[openapi(paths(...))]\`"
echo "   - Add types to \`routes.rs\` \`#[openapi(components(schemas(...)))]\`"
echo "   - Run \`./scripts/ci/check_openapi_drift.sh --fix\`"
echo ""
echo "2. **Modifying request/response types:**"
echo "   - Update types in \`adapteros-api-types\`"
echo "   - Regenerate OpenAPI spec"
echo "   - Rebuild WASM UI: \`trunk build\`"
echo ""
echo "3. **Changing auth requirements:**"
echo "   - Update middleware in route registration"
echo "   - Update \`smoke_e2e.sh\` test expectations"
echo ""

echo "---"
echo ""
echo "*Generated by \`scripts/docs/generate_route_map.sh\`*"
