import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gotoAndBootstrap } from './utils';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..', '..', '..');
const outPath = path.resolve(repoRoot, 'var', 'button-map.md');

type Entry = {
  route: string;
  kind: 'link' | 'button';
  name: string;
  href?: string | null;
  disabled?: boolean;
  dataTestid?: string | null;
};

async function collectButtonsAndLinks(page: Page): Promise<Entry[]> {
  return await page.evaluate(() => {
    const visible = (el: Element) => {
      const h = el as HTMLElement;
      const style = window.getComputedStyle(h);
      if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
        return false;
      }
      const r = h.getBoundingClientRect();
      return r.width > 0 && r.height > 0;
    };

    const nameOf = (el: Element) => {
      const h = el as HTMLElement;
      const aria = h.getAttribute('aria-label');
      const text = (h.textContent ?? '').replace(/\s+/g, ' ').trim();
      return (aria && aria.trim()) || text;
    };

    const entries: any[] = [];
    const buttons = Array.from(document.querySelectorAll('button')).filter(visible);
    for (const b of buttons) {
      entries.push({
        kind: 'button',
        name: nameOf(b),
        disabled: (b as HTMLButtonElement).disabled || b.getAttribute('aria-disabled') === 'true',
        dataTestid: b.getAttribute('data-testid'),
      });
    }

    const links = Array.from(document.querySelectorAll('a[href]')).filter(visible);
    for (const a of links) {
      entries.push({
        kind: 'link',
        name: nameOf(a),
        href: (a as HTMLAnchorElement).getAttribute('href'),
        dataTestid: a.getAttribute('data-testid'),
      });
    }

    // Dedup noisy duplicates by kind+name+href.
    const seen = new Set<string>();
    return entries.filter((e) => {
      const key = `${e.kind}::${e.name}::${e.href ?? ''}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  });
}

test('button map (demo surfaces)', { tag: ['@map'] }, async ({ page }) => {
  test.setTimeout(6 * 60_000);

  const routes = ['/documents', '/training', '/chat', '/runs'];
  const report: Entry[] = [];

  for (const route of routes) {
    await gotoAndBootstrap(page, route, { mode: 'ui-only' });
    await expect(page.locator('body')).toBeVisible();

    const entries = await collectButtonsAndLinks(page);
    for (const e of entries) {
      report.push({ ...e, route });
    }
  }

  const lines: string[] = [];
  lines.push('# Button Map (Demo Surfaces)');
  lines.push('');
  lines.push('Generated by Playwright: `tests/playwright/ui/button_map.spec.ts`');
  lines.push('');

  for (const route of routes) {
    lines.push(`## ${route}`);
    lines.push('');
    const items = report.filter((r) => r.route === route);
    for (const item of items) {
      const name = item.name || '(no label)';
      const testid = item.dataTestid ? ` data-testid=${item.dataTestid}` : '';
      if (item.kind === 'link') {
        lines.push(`- link: \`${name}\`${testid} -> \`${item.href ?? ''}\``);
      } else {
        const state = item.disabled ? 'disabled' : 'enabled';
        lines.push(`- button: \`${name}\`${testid} (${state})`);
      }
    }
    lines.push('');
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
});
