#!/usr/bin/env bash
# PRD-UI-000: CI Gate - Validate UI Assets Integrity
#
# This script verifies that:
# 1. WASM file exists with correct magic number (0x00asm)
# 2. CSS files exist and are non-empty
# 3. index.html references hashed assets
# 4. All expected asset files are present

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATIC_DIR="$ROOT_DIR/crates/adapteros-server/static"

cd "$ROOT_DIR"
export LC_ALL=C
export LANG=C

echo "=== PRD-UI-000: UI Assets Integrity Check ==="
echo ""

# Track errors
ERRORS=0

# Helper function to log errors
log_error() {
    echo "ERROR: $1"
    ERRORS=$((ERRORS + 1))
}

log_success() {
    echo "OK: $1"
}

log_info() {
    echo "INFO: $1"
}

# Check if static directory exists
if [ ! -d "$STATIC_DIR" ]; then
    log_error "Static directory not found at $STATIC_DIR"
    echo ""
    echo "Run 'trunk build --release' in crates/adapteros-ui/ first."
    exit 1
fi

echo "Checking directory: $STATIC_DIR"
echo ""

# 1. Check WASM file exists and has correct magic number
echo "--- WASM Validation ---"
WASM_FILES=("$STATIC_DIR"/*.wasm)
if [ ! -e "${WASM_FILES[0]}" ]; then
    log_error "No .wasm files found in $STATIC_DIR"
else
    for wasm_file in "${WASM_FILES[@]}"; do
        if [ -f "$wasm_file" ]; then
            # Check WASM magic number: 0x00 0x61 0x73 0x6d (null + "asm")
            MAGIC=$(xxd -l 4 -p "$wasm_file" 2>/dev/null || echo "error")
            if [ "$MAGIC" = "0061736d" ]; then
                WASM_SIZE=$(stat -f%z "$wasm_file" 2>/dev/null || stat -c%s "$wasm_file" 2>/dev/null || echo "unknown")
                log_success "WASM file valid: $(basename "$wasm_file") (${WASM_SIZE} bytes)"
            else
                log_error "Invalid WASM magic number in $(basename "$wasm_file"): expected 0061736d, got $MAGIC"
            fi
        fi
    done
fi
echo ""

# 2. Check CSS files exist and are non-empty
echo "--- CSS Validation ---"
CSS_FILES=("$STATIC_DIR"/*.css)
if [ ! -e "${CSS_FILES[0]}" ]; then
    log_error "No .css files found in $STATIC_DIR"
else
    for css_file in "${CSS_FILES[@]}"; do
        if [ -f "$css_file" ]; then
            CSS_SIZE=$(stat -f%z "$css_file" 2>/dev/null || stat -c%s "$css_file" 2>/dev/null || echo "0")
            if [ "$CSS_SIZE" -gt 0 ]; then
                log_success "CSS file valid: $(basename "$css_file") (${CSS_SIZE} bytes)"
            else
                log_error "Empty CSS file: $(basename "$css_file")"
            fi
        fi
    done
fi
echo ""

# 3. Check index.html exists and references hashed assets
echo "--- index.html Validation ---"
INDEX_FILE="$STATIC_DIR/index.html"
if [ ! -f "$INDEX_FILE" ]; then
    log_error "index.html not found in $STATIC_DIR"
else
    INDEX_SIZE=$(stat -f%z "$INDEX_FILE" 2>/dev/null || stat -c%s "$INDEX_FILE" 2>/dev/null || echo "0")
    if [ "$INDEX_SIZE" -gt 0 ]; then
        log_success "index.html exists (${INDEX_SIZE} bytes)"
    else
        log_error "index.html is empty"
    fi

    # Check for hashed asset references (Trunk adds hashes like -abc123.wasm)
    if grep -qE '\.(wasm|js|css)' "$INDEX_FILE"; then
        log_success "index.html contains asset references"
    else
        log_error "index.html does not contain expected asset references (.wasm, .js, .css)"
    fi

    # Check for WASM reference specifically
    if grep -qE '\.wasm' "$INDEX_FILE"; then
        WASM_REF=$(grep -oE '[a-zA-Z0-9_-]+\.wasm' "$INDEX_FILE" | head -1)
        log_success "WASM reference found: $WASM_REF"
    else
        log_error "No .wasm reference found in index.html"
    fi

    # Check for boot metadata (PRD-UI-000 enhancement)
    if grep -q 'aos-build-hash' "$INDEX_FILE"; then
        log_success "Build hash metadata present"
    else
        log_info "Build hash metadata not found (optional)"
    fi
fi
echo ""

# 4. Check for JS glue file (generated by wasm-bindgen)
echo "--- JavaScript Validation ---"
JS_FILES=("$STATIC_DIR"/*.js)
if [ ! -e "${JS_FILES[0]}" ]; then
    log_info "No .js files found (may be inlined in WASM)"
else
    for js_file in "${JS_FILES[@]}"; do
        if [ -f "$js_file" ]; then
            JS_SIZE=$(stat -f%z "$js_file" 2>/dev/null || stat -c%s "$js_file" 2>/dev/null || echo "0")
            if [ "$JS_SIZE" -gt 0 ]; then
                log_success "JS file valid: $(basename "$js_file") (${JS_SIZE} bytes)"
            else
                log_error "Empty JS file: $(basename "$js_file")"
            fi
        fi
    done
fi
echo ""

# 5. Validate SRI digests match on-disk assets
echo "--- SRI Validation ---"
if command -v openssl >/dev/null 2>&1 && command -v perl >/dev/null 2>&1; then
    if [ -f "$INDEX_FILE" ]; then
        while read -r asset integrity; do
            if [ -z "$asset" ] || [ -z "$integrity" ]; then
                continue
            fi
            asset_path="$STATIC_DIR/$asset"
            if [ ! -f "$asset_path" ]; then
                log_error "Integrity entry refers to missing asset: $asset"
                continue
            fi
            actual="sha384-$(openssl dgst -sha384 -binary "$asset_path" | base64)"
            if [ "$actual" = "$integrity" ]; then
                log_success "SRI ok: $asset"
            else
                log_error "SRI mismatch for $asset (index=$integrity, actual=$actual)"
            fi
        done < <(perl -ne 'while (/href="\/([^"]+)"[^>]*integrity="(sha384-[^"]+)"/g){print "$1 $2\n"}' "$INDEX_FILE")
    else
        log_error "index.html missing; cannot validate integrity attributes"
    fi
else
    log_info "Skipping SRI validation (openssl/perl not available)"
fi
echo ""

# 6. Summary
echo "=== Summary ==="
if [ $ERRORS -eq 0 ]; then
    echo "All UI asset checks passed!"
    echo ""
    exit 0
else
    echo "Found $ERRORS error(s) in UI assets"
    echo ""
    exit 1
fi
