/**
 * UI Types Root Barrel Export
 *
 * This module contains all UI-specific types that are NOT directly derived
 * from the backend API. For API-generated types, see ../api/api-types.ts
 *
 * Directory Structure:
 * - common/      - Shared utility and API wrapper types
 * - components/  - React component prop types
 * - display/     - Data formatting and status display types
 * - forms/       - Form and input field types
 * - hooks/       - Custom React hook types
 * - state/       - UI state management types
 *
 * See README.md in this directory for detailed documentation.
 */

// Root-level UI types
export * from './chat';
export * from './session-scope';
export * from './utilities';

// Export from history with conflict resolution
export type {
  ActionHistoryItem,
  ActionStats,
  HistoryExportOptions,
  HistoryFilterOptions,
  HistoryReplayOptions,
  HistorySearchOptions,
  HistoryStorageOptions,
  ReplayResult,
  ActionStatus,
  ActionType,
  ResourceType,
} from './history';
// Re-export PaginationOptions from history as HistoryPaginationOptions
export type { PaginationOptions as HistoryPaginationOptions } from './history';

// Export from service-lifecycle with conflict resolution
export type {
  HealthCheck,
  LifecycleEvent,
  LifecycleHook,
  RestartOptions,
  Service,
  ServiceCluster,
  ServiceConfiguration,
  ServiceDependency,
  ServiceGroup,
  ServiceLogEntry,
  ServiceManagerConfig,
  ServiceMetrics,
  StartOptions,
  StopOptions,
  LifecyclePhase,
  ServiceStatus,
} from './service-lifecycle';
// Re-export HealthStatus from service-lifecycle as ServiceHealthStatus
export type { HealthStatus as ServiceHealthStatus } from './service-lifecycle';

// Organized type subdirectories
export * from './common';
export * from './forms';

// Export components with conflict resolution
export type {
  StackAdapter,
  AdapterImportWizardProps,
  AdapterStackComposerProps,
  AdapterLifecycleManagerProps,
  AdapterMemoryMonitorProps,
  SortableAdapterItemProps,
  AdapterStateVisualizationProps,
  DomainAdapterDomain,
  DomainAdapter,
  DomainAdapterManagerProps,
  AdapterLoadingStatusProps,
  AdapterLoadingProgressProps,
  MissingPinnedAdaptersBannerProps,
  WizardState,
  DatasetSummary,
  TrainingWizardProps,
  TrainingMonitorProps,
  MetricsComparisonProps,
  PublishAdapterDialogProps,
  PreprocessingOptions,
  TokenizationSettings,
  DatasetConfigData,
  DatasetConfigProps,
  DatasetSelectorProps,
  TrainingMetricsDisplayProps,
  DatasetPreviewProps,
  DatasetStatsProps,
  QuickTrainConfirmModalProps,
  TrainingComparisonProps,
  DatasetVersionPickerProps,
  DatasetSplitConfigProps,
  EvidenceItem,
  ThroughputStats,
  ChatMessage,
  ChatInterfaceProps,
  ChatMessageProps,
  ChatSearchBarProps,
  ChatArchivePanelProps,
  SessionCardProps,
  EvidenceDrawerProps,
  EvidenceDrawerTab,
  RulebookTabProps,
  CalculationTabProps,
  TraceTabProps,
  EvidenceDrawerTriggerProps,
  ReplayButtonProps,
  ChatErrorDisplayProps,
  ChatLoadingOverlayProps,
  ChatTimeoutWarningProps,
  ChatSessionActionsProps,
  ChatTagsManagerProps,
  ChatCategoriesManagerProps,
  PreChatAdapterPromptProps,
  MissingPinnedAdaptersWarningProps,
  SimplifiedChatWidgetProps,
  RouterActivitySidebarProps,
  ChatInitialLoadStateProps,
  MetricData,
  MetricsChartProps,
  ResourceMetrics,
  NodeInfo,
  ResourceMonitorProps,
  DashboardProps,
  DashboardLayoutProps,
  MetricCardData,
  MetricsCardProps,
  AlertData,
  AlertListProps,
  DashboardWidgetFrameProps,
  DashboardSettingsProps,
  RoleDashboardProps,
  SREDashboardProps,
  OperatorDashboardProps,
  ComplianceDashboardProps,
  ITAdminDashboardProps,
  SystemHealthStatus,
  HealthStatusProps,
  RealtimeMetricsProps,
  TelemetryViewerProps,
  AlertProps,
  BadgeProps,
  BreadcrumbsProps,
  ButtonProps,
  CardProps,
  DialogProps,
  EmptyStateProps,
  LoadingSpinnerProps,
  PageProps,
  ProgressBarProps,
  TableColumn,
  TableProps,
  TabProps,
} from './components';
// Re-export ChartDataPoint from components as ComponentChartDataPoint
export type { ChartDataPoint as ComponentChartDataPoint } from './components';
// Re-export BreadcrumbItem from components as ComponentBreadcrumbItem
export type { BreadcrumbItem as ComponentBreadcrumbItem } from './components';

// Export display with conflict resolution
export type {
  ChartSeries,
  ColorScheme,
  DisplayValue,
  FormatBytesOptions,
  FormatDateOptions,
  FormatDurationOptions,
  FormatNumberOptions,
  MetricDisplay,
  StatusDisplay,
  TableCellDisplay,
  ByteFormat,
  DateFormat,
  NumberFormat,
  ConnectionInfo,
  HealthCheckResult,
  ProgressIndicator,
  StatusBadgeProps,
  StatusIndicatorProps,
  SyncInfo,
  SystemHealth,
  WorkflowStatus,
  WorkflowStepStatus,
  LoadingStatus,
  OperationStatus,
  SyncStatus,
} from './display';
// Re-export ChartDataPoint from display (the formatting one, preferred)
export type { ChartDataPoint } from './display';
// Re-export HealthStatus from display (the status one, preferred)
export type { HealthStatus } from './display';
// Re-export ConnectionStatus from display (preferred)
export type { ConnectionStatus } from './display';

// Export hooks with conflict resolution
export type {
  UseAdapterActionsOptions,
  UseAdapterBulkActionsOptions,
  UseAdapterBulkActionsReturn,
  UseAdapterDetailOptions,
  UseAdapterDetailReturn,
  UseAdapterDialogsReturn,
  UseAdapterExportOptions,
  UseAdapterExportReturn,
  UseAdapterFilterStateOptions,
  UseAdapterFilterStateReturn,
  UseAdapterOperationsOptions,
  UseAdapterOperationsReturn,
  AsyncActionState,
  UseAsyncActionOptions,
  UseAsyncActionReturn,
  UseAsyncOperationOptions,
  UseAsyncOperationReturn,
  UseCancellableOperationReturn,
  UseRetryOptions,
  UseRetryReturn,
  UseChatAdapterStateOptions,
  UseChatAdapterStateReturn,
  UseChatInitialLoadOptions,
  UseChatRouterDecisionsOptions,
  UseChatRouterDecisionsReturn,
  UseChatSearchOptions,
  UseChatSearchReturn,
  UseChatSessionsOptions,
  UseChatStreamingOptions,
  UseChatStreamingReturn,
  UseMessagesOptions,
  UseMessagesReturn,
  UseSessionManagerOptions,
  UseClickOutsideOptions,
  UseClipboardResult,
  UseDebounceOptions,
  UseFormFieldConfig,
  UseFormValidationRule,
  UseIntersectionObserverOptions,
  UseIntersectionObserverResult,
  UseLocalStorageOptions,
  UseLocalStorageResult,
  UseMediaQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UsePaginationOptions,
  UsePaginationResult,
  UseQueryOptions,
  UseQueryResult,
  UseThrottleOptions,
  UseWebSocketOptions,
  UseWebSocketResult,
  UseAdapterSelectionOptions,
  UseAdapterSelectionReturn,
  UseBackendSelectionOptions,
  UseBackendSelectionReturn,
  UseBatchInferenceOptions,
  UseBatchInferenceReturn,
  UseCoreMLManagementOptions,
  UseCoreMLManagementReturn,
  UseInferenceConfigOptions,
  UseInferenceConfigReturn,
  UseInferenceSessionsOptions,
  UseInferenceSessionsReturn,
  UseInferenceUrlStateReturn,
  UseStreamingInferenceOptions,
  UseStreamingInferenceReturn,
  UseAdapterStatesOptions,
  UseAdapterStatesResult,
  UseAutoLoadModelReturn,
  UseChatLoadingPersistenceOptions,
  UseChatLoadingPersistenceReturn,
  UseLoadingAnnouncementsOptions,
  UseLoadingAnnouncementsResult,
  UseModelLoaderResult,
  UseModelLoadingStateOptions,
  UseModelLoadingStateResult,
  UseModelStatusReturn,
  ModelLoadingStatus,
  UseActivityEventsOptions,
  UseActivityEventsReturn,
  UseActivityFeedOptions,
  UseActivityFeedReturn,
  UseLiveDataOptions,
  UseLiveDataReturn,
  UseNotificationsOptions,
  UseNotificationsReturn,
  UsePollingReturn,
  UseSessionTelemetryOptions,
  UseSessionTelemetryResult,
  UseSSEOptions,
  UseSSEWithPollingFallbackOptions,
  UseSSEWithPollingFallbackReturn,
  DataFreshnessLevel,
  PollingSpeed,
  TrainingPreflightResult,
  UseBatchedTrainingNotificationsOptions,
  UseTrainingJobOptions,
  UseTrainingJobReturn,
  UseTrainingMonitorReturn,
  UseTrainingNotificationsOptions,
  UseTrainingPreflightOptions,
  BulkActionError,
  BulkActionOptions,
  BulkActionProgress,
  BulkActionResult,
  ConfirmationOptions,
  UseBulkActionsOptions,
  UseBulkActionsReturn,
  UseConfirmationReturn,
  UseDataLoaderOptions,
  UseDataLoaderReturn,
  UseDebouncedValueOptions,
  UseDebouncedValueReturn,
  UseFilterOptions,
  UseFilterReturn,
  UseInfiniteScrollOptions,
  UseInfiniteScrollReturn,
  UseInformationDensityReturn,
  UseProgressOperationReturn,
  UseSelectionOptions,
  UseSelectionReturn,
  UseSortOptions,
  UseSortReturn,
  BulkActionStatus,
  InformationDensity,
  PageParam,
} from './hooks';
// Re-export hook duplicates with Hook prefix (hooks take precedence for these)
export type { AsyncOperationState as HookAsyncOperationState } from './hooks';
export type { BulkActionConfirmationState as HookBulkActionConfirmationState } from './hooks';
export type { BulkOperationProgress as HookBulkOperationProgress } from './hooks';
export type { PaginationOptions as HookPaginationOptions } from './hooks';
export type { PaginationState as HookPaginationState } from './hooks';
export type { RetryConfig as HookRetryConfig } from './hooks';
export type { RetryState as HookRetryState } from './hooks';
export type { ConnectionStatus as HookConnectionStatus } from './hooks';

// Export state types (preferred for state management patterns)
export type {
  SelectionState,
  SelectionActions,
  SelectionStateWithActions,
  MultiSelectConfig,
  SelectionMode,
  SelectionStateWithMode,
  SortState,
  SortActions,
  FilterState,
  FilterActions,
  SearchState,
  SearchActions,
  FilteredListState,
  FilteredListActions,
  FilteredListStateWithActions,
  FilterPreset,
  FilterPresetManager,
  ModalState,
  ModalActions,
  ModalStateWithActions,
  DialogState,
  DialogActions,
  DialogStateWithActions,
  ConfirmationDialogData,
  ConfirmationDialogState,
  MultiStepDialogState,
  MultiStepDialogActions,
  DrawerState,
  DrawerActions,
  DrawerStateWithActions,
  ToastState,
  ToastManager,
  PanelState,
  PanelActions,
  PanelStateWithActions,
  AsyncOperationActions,
  AsyncOperationStateWithActions,
  CancellableOperationState,
  CancellableOperationActions,
  ProgressState,
  LoadingStateWithProgress,
  OptimisticUpdateState,
  OptimisticUpdateActions,
  DebouncedState,
  DebouncedActions,
  AsyncStatus,
  BreadcrumbState,
  NavigationTab,
  TabNavigationState,
  TabNavigationActions,
  NavigationHistoryState,
  NavigationHistoryActions,
  SidebarState,
  SidebarActions,
  SidebarStateWithActions,
  RouteParamState,
  NavigationContext,
  StateSlice,
  PersistedStateConfig,
  FeatureFlags,
  FeatureFlagManager,
  BulkActionConfig,
  BulkActionHookResult,
  BulkOperationResult,
  BulkOperationState,
  BulkSelectionState,
  BulkOperationType,
} from './state';
// Re-export state types that are preferred from state module
export type { AsyncOperationState } from './state';
export type { BulkActionConfirmationState } from './state';
export type { BulkOperationProgress } from './state';
export type { PaginationState } from './state';
export type { PaginationActions } from './state';
export type { RetryConfig } from './state';
export type { RetryState } from './state';
export type { RetryActions } from './state';
export type { BreadcrumbItem } from './state';
