//! System initialization command for Owner Home feature
//!
//! This command performs initial system setup:
//! - Runs database migrations
//! - Creates default "system" tenant
//! - Creates owner user with admin role
//! - Generates secure credentials
//! - Writes configuration to ~/.aos/config.toml

use crate::output::OutputWriter;
use adapteros_db::{users::Role, Db};
use anyhow::{anyhow, bail, Context, Result};
use argon2::{
    password_hash::{PasswordHasher, SaltString},
    Argon2,
};
use clap::Args;
use rand::{distributions::Alphanumeric, rngs::OsRng, Rng};
use serde::Serialize;
use std::fs;
use std::path::PathBuf;
use std::time::Duration;
use tracing::{debug, error, info, warn};

#[derive(Args, Debug, Clone)]
pub struct InitArgs {
    /// Database URL (default: sqlite://var/aos-cp.sqlite3)
    #[arg(long, env = "DATABASE_URL")]
    pub database_url: Option<String>,

    /// Owner email address
    #[arg(long, default_value = "owner@localhost")]
    pub owner_email: String,

    /// Owner display name (defaults to derived from email)
    #[arg(long)]
    pub owner_name: Option<String>,

    /// Skip interactive prompts
    #[arg(long, short = 'y')]
    pub yes: bool,

    /// Skip creating config file
    #[arg(long)]
    pub skip_config: bool,

    /// UI server URL (default: http://localhost:5173)
    #[arg(long, default_value = "http://localhost:5173")]
    pub ui_url: String,

    /// API server URL (default: http://localhost:8080)
    #[arg(long, default_value = "http://localhost:8080")]
    pub api_url: String,
}

#[derive(Serialize)]
struct InitResponse {
    tenant_id: String,
    user_id: String,
    email: String,
    display_name: String,
    role: String,
    password: String,
    ui_url: String,
    api_url: String,
    config_path: String,
    instructions: Vec<String>,
}

/// Derive display name from email
fn derive_display_name(email: &str) -> String {
    email
        .split('@')
        .next()
        .map(|prefix| {
            if prefix.is_empty() {
                email.to_string()
            } else {
                prefix
                    .split(['.', '_', '-'])
                    .filter(|segment| !segment.is_empty())
                    .map(|segment| {
                        let mut chars = segment.chars();
                        match chars.next() {
                            Some(first) => {
                                let mut title = first.to_uppercase().collect::<String>();
                                title.push_str(&chars.as_str().to_lowercase());
                                title
                            }
                            None => String::new(),
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(" ")
            }
        })
        .unwrap_or_else(|| email.to_string())
}

/// Generate a secure random password
fn generate_password() -> String {
    let rng = OsRng;
    rng.sample_iter(&Alphanumeric)
        .take(24)
        .map(char::from)
        .collect()
}

/// Get or create default config directory
fn get_config_dir() -> Result<PathBuf> {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .context("Failed to determine home directory")?;
    let config_dir = PathBuf::from(home).join(".aos");

    if !config_dir.exists() {
        fs::create_dir_all(&config_dir).context("Failed to create config directory")?;
    }

    Ok(config_dir)
}

/// Write configuration to ~/.aos/config.toml
fn write_config(
    db_url: &str,
    api_url: &str,
    ui_url: &str,
    output: &OutputWriter,
) -> Result<PathBuf> {
    let config_dir = get_config_dir()?;
    let config_path = config_dir.join("config.toml");

    let config_content = format!(
        r#"# adapterOS Configuration
# Generated by: aosctl init
# Last updated: {}

[database]
url = "{}"

[api]
url = "{}"

[ui]
url = "{}"

[defaults]
tenant_id = "system"
"#,
        chrono::Utc::now().to_rfc3339(),
        db_url,
        api_url,
        ui_url,
    );

    fs::write(&config_path, config_content).context("Failed to write config file")?;

    output.verbose(format!("Config written to: {}", config_path.display()));

    Ok(config_path)
}

/// Test connectivity to the API server (checks both /healthz and /v1/meta)
async fn test_api_connectivity(api_url: &str, timeout_secs: u64) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(timeout_secs))
        .build()
        .context("Failed to create HTTP client")?;

    let base = api_url.trim_end_matches('/');

    // Check /healthz
    let healthz_url = format!("{}/healthz", base);
    let response = client
        .get(&healthz_url)
        .send()
        .await
        .context("Could not connect to server /healthz")?;

    if !response.status().is_success() {
        bail!("Server /healthz returned {}", response.status());
    }

    // Check /v1/meta
    let meta_url = format!("{}/v1/meta", base);
    let response = client
        .get(&meta_url)
        .send()
        .await
        .context("Could not connect to server /v1/meta")?;

    if !response.status().is_success() {
        bail!("Server /v1/meta returned {}", response.status());
    }

    Ok(())
}

/// Run the init command
pub async fn run(args: InitArgs, output: &OutputWriter) -> Result<()> {
    info!(email = %args.owner_email, "Starting system initialization");

    // Step 1: Validate email
    if args.owner_email.trim().is_empty() {
        error!("Owner email validation failed: empty email");
        bail!("Owner email must not be empty");
    }
    debug!(email = %args.owner_email, "Email validation passed");

    // Determine database URL
    let db_url = args
        .database_url
        .clone()
        .unwrap_or_else(|| "sqlite://./var/aos-cp.sqlite3".to_string());
    debug!(db_url = %db_url, "Using database URL");

    // Step 2: Check if already initialized (unless --yes)
    if !args.yes {
        debug!("Checking for existing initialization");
        match Db::connect(&db_url).await {
            Ok(db) => {
                let user_count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users")
                    .fetch_one(db.pool())
                    .await
                    .unwrap_or(0);

                if user_count > 0 {
                    warn!(
                        user_count = user_count,
                        "System already initialized with existing users"
                    );
                    output.warning("System appears to be already initialized");
                    output.warning(format!("Found {} existing users", user_count));
                    output.info("");
                    output.info("Continue anyway? (y/N): ");

                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;

                    if input.trim().to_lowercase() != "y" {
                        info!("Initialization cancelled by user");
                        output.info("Initialization cancelled");
                        return Ok(());
                    }
                    info!("User chose to continue despite existing initialization");
                }
            }
            Err(_) => {
                debug!("Database does not exist yet, will be created");
                // Database doesn't exist yet, which is fine
            }
        }
    }

    output.info("Initializing adapterOS system...");
    output.blank();

    // Step 2.5: Test API server connectivity (informational)
    output.progress("Testing API server connectivity...");
    match test_api_connectivity(&args.api_url, 5).await {
        Ok(_) => {
            info!(api_url = %args.api_url, "API server reachable");
            output.success(format!("Server reachable at {}", args.api_url));
        }
        Err(e) => {
            warn!(api_url = %args.api_url, error = %e, "API server not reachable");
            output.warning(format!("Could not connect to server: {}", e));
            output.info("");
            output.info("The server may not be running yet.");
            output.info("To start the server: cargo run --release -p adapteros-server");
            output.info("");
            if !args.yes {
                output.info("Continue with setup anyway? (y/N): ");
                let mut input = String::new();
                std::io::stdin().read_line(&mut input)?;
                if input.trim().to_lowercase() != "y" {
                    info!("Init cancelled by user - server not reachable");
                    output.info("Initialization cancelled");
                    return Ok(());
                }
            }
        }
    }
    output.blank();

    // Step 3: Run database migrations
    info!(db_url = %db_url, "Connecting to database and running migrations");
    output.progress("Running database migrations...");
    let db = Db::connect(&db_url)
        .await
        .context("Failed to connect to database")?;
    debug!("Database connection established");

    db.migrate()
        .await
        .context("Failed to run database migrations")?;

    info!("Database migrations completed successfully");
    output.success("Database migrations completed");

    // Step 4: Create default "system" tenant
    info!("Creating or verifying default tenant");
    output.progress("Creating default tenant...");

    let tenant_id = match db.get_tenant("system").await? {
        Some(tenant) => {
            debug!(tenant_id = %tenant.id, "Default tenant 'system' already exists");
            output.verbose("Default tenant 'system' already exists");
            tenant.id
        }
        None => {
            let id = db
                .create_tenant("system", false)
                .await
                .context("Failed to create default tenant")?;
            info!(tenant_id = %id, "Created default tenant 'system'");
            output.success("Created default tenant 'system'");
            id
        }
    };

    // Step 5: Create owner user
    info!(email = %args.owner_email, "Creating owner user");
    output.progress("Creating owner user...");

    // Check if user already exists
    if let Some(existing_user) = db.get_user_by_email(&args.owner_email).await? {
        warn!(
            email = %args.owner_email,
            user_id = %existing_user.id,
            "User already exists"
        );
        output.warning(format!(
            "User with email '{}' already exists (ID: {})",
            args.owner_email, existing_user.id
        ));

        if !args.yes {
            error!("Initialization aborted: user already exists and --yes not specified");
            bail!("User already exists. Use a different email or run with --yes to continue");
        }

        // If --yes, we'll just report the existing credentials (but can't retrieve password)
        info!("Continuing with existing user due to --yes flag");
        output.warning("Cannot retrieve existing password. Please use password reset if needed.");
        output.blank();

        if output.is_json() {
            let response = InitResponse {
                tenant_id: tenant_id.clone(),
                user_id: existing_user.id,
                email: existing_user.email,
                display_name: existing_user.display_name,
                role: existing_user.role,
                password: "[existing - cannot retrieve]".to_string(),
                ui_url: args.ui_url.clone(),
                api_url: args.api_url.clone(),
                config_path: get_config_dir()?.join("config.toml").display().to_string(),
                instructions: vec![
                    "User already exists".to_string(),
                    "Use password reset to recover access".to_string(),
                ],
            };
            output.json(&response)?;
        }

        return Ok(());
    }

    // Derive display name
    let display_name = args
        .owner_name
        .clone()
        .filter(|name| !name.trim().is_empty())
        .unwrap_or_else(|| derive_display_name(&args.owner_email));
    debug!(display_name = %display_name, "Derived display name");

    // Generate secure password
    debug!("Generating secure password");
    let password = generate_password();

    // Hash password
    debug!("Hashing password with Argon2");
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    let password_hash = argon2
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| {
            error!(error = %e, "Failed to hash password");
            anyhow!("Failed to hash password: {}", e)
        })?
        .to_string();

    // Create user
    let user_id = db
        .create_user(
            &args.owner_email,
            &display_name,
            &password_hash,
            Role::Admin,
            "system",
        )
        .await
        .context("Failed to create owner user")?;

    info!(
        user_id = %user_id,
        email = %args.owner_email,
        tenant_id = "system",
        role = "admin",
        "Owner user created successfully"
    );
    output.success("Owner user created");

    // Step 6: Write config file (unless --skip-config)
    let config_path = if args.skip_config {
        debug!("Skipping config file creation (--skip-config specified)");
        output.verbose("Skipping config file creation");
        PathBuf::from("[skipped]")
    } else {
        info!("Writing configuration file");
        output.progress("Writing configuration...");
        let path = write_config(&db_url, &args.api_url, &args.ui_url, output)
            .context("Failed to write config file")?;
        info!(config_path = %path.display(), "Configuration file created");
        output.success("Configuration file created");
        path
    };

    // Step 7: Print success message with credentials
    output.blank();

    if output.is_json() {
        let response = InitResponse {
            tenant_id: tenant_id.clone(),
            user_id: user_id.clone(),
            email: args.owner_email.clone(),
            display_name: display_name.clone(),
            role: Role::Admin.to_string(),
            password: password.clone(),
            ui_url: args.ui_url.clone(),
            api_url: args.api_url.clone(),
            config_path: config_path.display().to_string(),
            instructions: vec![
                "Store the password securely".to_string(),
                "Change the password after first login".to_string(),
                format!("Access the UI at: {}", args.ui_url),
            ],
        };
        output.json(&response)?;
    } else {
        output.success("adapterOS initialization complete!");
        output.blank();
        output.result("=".repeat(60));
        output.result("  OWNER CREDENTIALS");
        output.result("=".repeat(60));
        output.blank();
        output.kv("Tenant ID", &tenant_id);
        output.kv("Email", &args.owner_email);
        output.kv("Display Name", &display_name);
        output.kv("Role", "admin");
        output.kv("Password", &password);
        output.blank();
        output.result("=".repeat(60));
        output.result("  SYSTEM URLS");
        output.result("=".repeat(60));
        output.blank();
        output.kv("UI", &args.ui_url);
        output.kv("API", &args.api_url);
        output.blank();
        output.result("=".repeat(60));
        output.result("  NEXT STEPS");
        output.result("=".repeat(60));
        output.blank();
        output.result("1. Start the API server: cargo run -p adapteros-server-api");
        output.result("2. Start the UI: cd ui && pnpm dev");
        output.result(format!("3. Access the UI at: {}", args.ui_url));
        output.result("4. Login with the credentials above");
        output.result("5. Change your password after first login");
        output.blank();
        output.warning("IMPORTANT: Store the password securely!");
        output.warning("           This password will not be shown again.");
        output.blank();

        if !args.skip_config {
            output.info(format!("Configuration saved to: {}", config_path.display()));
        }
    }

    info!(
        tenant_id = %tenant_id,
        user_id = %user_id,
        email = %args.owner_email,
        "System initialization completed successfully"
    );

    Ok(())
}
