//! CLI command implementations

pub mod adapter;
pub mod adapter_codebase;
pub mod adapter_info;
pub mod adapter_migrate_hashes;
pub mod adapter_repair_hashes;
pub mod adapter_swap;
pub mod adapters;
pub mod agent;
pub mod aos;
pub mod session;
pub mod worker_executor;

pub mod aos_impl;
pub mod audit;
pub mod audit_determinism;
pub mod auth_cli;
pub mod backend_status;
pub mod bootstrap;
pub mod bootstrap_admin;
pub mod build_plan;
pub mod cdp_list;
pub mod chat;
pub mod check;
pub mod check_tokenizer;
pub mod code;
#[cfg(feature = "codegraph")]
pub mod codegraph;
pub mod completions;
pub mod config;
#[cfg(feature = "coreml-export")]
pub mod coreml_export;
pub mod coreml_status;
pub mod datasets;
pub mod db;
pub mod deploy;
pub mod dev;
pub mod diag;
pub mod diag_bundle;
pub mod diag_health;
pub mod doctor;
pub mod drift_check;
pub mod explain;
#[cfg(feature = "codegraph")]
pub mod export_callgraph;
pub mod federation;
pub mod golden;
pub mod import;
pub mod import_model;
pub mod infer;
pub mod ingest_docs;
pub mod init;
pub mod init_tenant;
pub mod list_adapters;
pub mod maintenance;
pub mod manual;
pub mod metrics; // Now uses adapteros_db::SystemMetricsDbOps
pub mod models;
pub mod node;
pub mod stack;
pub mod status;
// Legacy node commands - still used by app.rs standalone commands
// TODO: Migrate app.rs Commands::NodeList/NodeVerify/NodeSync to use node.rs subcommands
pub mod baseline;
#[cfg(feature = "orchestrator")]
pub mod behavior_export;
#[cfg(feature = "codegraph")]
pub mod codegraph_stats;
pub mod node_list;
pub mod node_sync;
pub mod node_verify;
pub mod pin;
pub mod policy;
pub mod preflight;
pub mod preflight_fix;
pub mod preflight_readiness;
pub mod profile;
pub mod quantize_qwen;
pub mod receipt_backfill;
pub mod recover;
pub mod register_adapter;
pub mod registry;
#[cfg(feature = "replay")]
pub mod replay;
#[cfg(feature = "replay")]
pub mod replay_bundle;
pub mod repo;
pub mod report;
pub mod review;
pub mod review_tui;
pub mod rollback;
pub mod router;
#[cfg(feature = "scenarios")]
pub mod scenario;
pub mod secd;
#[cfg(feature = "secd-support")]
pub mod secd_audit;
#[cfg(feature = "secd-support")]
pub mod secd_status;
pub mod serve;
pub mod storage;
pub mod telemetry;
pub mod telemetry_show;
#[cfg(feature = "trace")]
pub mod trace;
#[cfg(feature = "trace")]
pub mod trace_validate;
pub mod train;
pub mod train_base_adapter;
pub mod train_cli;
pub mod train_docs;
pub mod train_from_code;
pub mod training_common;

#[cfg(feature = "orchestrator")]
pub mod adapter_train_from_code;
#[cfg(feature = "tui")]
pub mod tui;
pub mod tutorial;
pub mod verify;
pub mod verify_adapter;
pub mod verify_adapters;
pub mod verify_cancellation_receipt;
pub mod verify_determinism_loop;
pub mod verify_gpu;
pub mod verify_receipt;

pub const NOT_IMPLEMENTED_ISSUE_URL: &str = "https://github.com/rogu3bear/adapter-os/issues/194";
pub const NOT_IMPLEMENTED_MESSAGE: &str =
    "This command is not yet implemented. Track progress at: https://github.com/rogu3bear/adapter-os/issues/194";
