#!/usr/bin/env bash
#
# UI dev server runner that respects the canonical port env vars:
# - AOS_UI_PORT (default 3200)
# - AOS_SERVER_PORT (default 8080)
# - AOS_SERVER_URL (optional full override, e.g. http://127.0.0.1:8180)
#
# Why: crates/adapteros-ui/Trunk.toml cannot interpolate env vars in proxy targets,
# so "port groups" break unless we generate a Trunk config with the right proxy.
#
# This script writes only to repo-local ./var/ (never /tmp).
#
# IMPORTANT: Dev builds are intentionally unoptimized (no wasm-opt) for fast iteration.
# To avoid polluting the backend's shipping static assets, we write Trunk outputs to
# ./var/trunk/dist instead of crates/adapteros-server/static.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UI_DIR="${ROOT}/crates/adapteros-ui"
VAR_DIR="${ROOT}/var/trunk"
CFG_PATH="${VAR_DIR}/Trunk.dev.toml"
DIST_DIR="${VAR_DIR}/dist"

trim_trailing_slashes() {
  echo "$1" | sed -E 's#/*$##'
}

normalize_backend_url() {
  local raw
  raw="$(trim_trailing_slashes "$1")"
  # Be forgiving if someone points AOS_SERVER_URL at /api.
  if [[ "$raw" == */api ]]; then
    raw="${raw%/api}"
  fi
  echo "$raw"
}

UI_PORT="${AOS_UI_PORT:-3200}"
BACKEND_URL="${AOS_SERVER_URL:-http://localhost:${AOS_SERVER_PORT:-8080}}"
BACKEND_URL="$(normalize_backend_url "$BACKEND_URL")"

mkdir -p "$VAR_DIR"
mkdir -p "$DIST_DIR"

# Generate a Trunk config with absolute paths so `--config` can live under var/.
cat >"$CFG_PATH" <<EOF
# Generated by scripts/ui-dev.sh. Do not edit by hand.

[build]
dist = "${DIST_DIR}"
public_url = "/"
no_wasm_opt = true

[[hooks]]
stage = "post_build"
command = "cp"
command_arguments = ["${ROOT}/crates/adapteros-ui/dist/sw.js", "${DIST_DIR}/sw.js"]

[watch]
watch = [
  "${ROOT}/crates/adapteros-ui/src",
  "${ROOT}/crates/adapteros-ui/index.html",
  "${ROOT}/crates/adapteros-ui/dist/base.css",
  "${ROOT}/crates/adapteros-ui/dist/glass.css",
  "${ROOT}/crates/adapteros-ui/dist/components.css",
  "${ROOT}/crates/adapteros-ui/dist/components",
  "${ROOT}/crates/adapteros-ui/dist/sw.js",
]
ignore = ["${ROOT}/crates/adapteros-ui/target"]

[serve]
port = ${UI_PORT}
proxy = [
  { path = "/api", address = "${BACKEND_URL}" },
  { path = "/v1", address = "${BACKEND_URL}" },
  { path = "/healthz", address = "${BACKEND_URL}" },
  { path = "/readyz", address = "${BACKEND_URL}" },
]
EOF

cd "$UI_DIR"
exec trunk serve --config "$CFG_PATH" "$@"
