//! Hardware-backed Secure Enclave operations for macOS
//!
//! This module provides direct integration with macOS Secure Enclave using CoreFoundation.
//! Implements full hardware-backed cryptographic operations per Secrets Ruleset #14.
//!
//! ## Capabilities
//!
//! - Hardware-backed Ed25519/ECDSA key generation in Secure Enclave
//! - Secure keychain persistence with hardware protection
//! - Hardware attestation data extraction
//! - ChaCha20Poly1305 key derivation from hardware sources
//!
//! ## Stub Implementation: SEP Attestation
//!
//! The [`SecureEnclaveConnection::get_real_sep_attestation`] method contains a stub
//! for real Secure Enclave Processor (SEP) attestation. When called, it falls back to
//! synthetic attestation generated by [`SecureEnclaveConnection::get_synthetic_attestation`].
//!
//! ### Why This Is a Stub
//!
//! Real SEP attestation via `SecKeyCopyAttestation` requires:
//!
//! 1. **macOS 13.0+ (Ventura)**: The API was introduced in macOS 13
//! 2. **FFI bindings**: Direct Security.framework FFI calls not exposed by `security-framework`
//! 3. **App entitlements**: Proper code signing with Secure Enclave entitlements
//! 4. **Hardware**: Apple Silicon (M1/M2/M3) or Intel Mac with T2 chip
//!
//! ### What Would Be Needed for Full Implementation
//!
//! 1. **FFI bindings to Security.framework**:
//!    ```rust,ignore
//!    extern "C" {
//!        fn SecKeyCopyAttestation(
//!            key: SecKeyRef,
//!            type_: CFStringRef,
//!            error: *mut CFErrorRef,
//!        ) -> CFDataRef;
//!    }
//!    ```
//!
//! 2. **Challenge data generation**: The attestation requires a nonce/challenge
//!
//! 3. **Attestation verification**: Parse and verify the Apple attestation format
//!
//! ### Current Stub Behavior
//!
//! The [`get_key_attestation`](SecureEnclaveConnection::get_key_attestation) method:
//! 1. First attempts `get_real_sep_attestation()` which returns an error (stub)
//! 2. Falls back to `get_synthetic_attestation()` which generates a self-signed
//!    attestation payload containing:
//!    - Public key bytes
//!    - ECDSA signature over (domain || alias || pubkey)
//!    - Timestamp
//!
//! The synthetic attestation proves the key exists and can sign, but does NOT
//! provide hardware attestation guarantees. It is suitable for development and
//! testing but should not be trusted for production key provenance verification.
//!
//! ### Platform Support
//!
//! | Platform | SEP Available | Attestation |
//! |----------|---------------|-------------|
//! | Apple Silicon Mac | Yes | Synthetic (stub) |
//! | Intel Mac with T2 | Yes | Synthetic (stub) |
//! | Intel Mac without T2 | No | Error |
//! | Non-macOS | No | Error |

use adapteros_core::{AosError, B3Hash, Result};
#[cfg(not(target_os = "macos"))]
use adapteros_crypto::Keypair;
use adapteros_crypto::{PublicKey, Signature};
use ed25519_dalek::{Signer, SigningKey};
use security_framework::access_control::{ProtectionMode, SecAccessControl};
use security_framework::item::Location;
use security_framework::item::{ItemClass, ItemSearchOptions, Reference, SearchResult};
use security_framework::key::{Algorithm, GenerateKeyOptions, KeyType, SecKey, Token};
use std::collections::HashMap;
#[cfg(not(target_os = "macos"))]
use tracing::warn;
use tracing::{debug, info, warn};

// Hardware integration constants and architectural patterns
/// Hardware-backed Secure Enclave connection
#[cfg_attr(target_os = "macos", derive(Debug))]
pub struct SecureEnclaveConnection {
    /// Cached keys by label for performance
    key_cache: HashMap<String, SecKey>,
}

/// Type alias exposed to callers for clarity.
pub type HardwareSecureEnclaveConnection = SecureEnclaveConnection;

#[cfg(target_os = "macos")]
const ERR_SEC_ITEM_NOT_FOUND: i32 = -25300;

#[cfg(target_os = "macos")]
impl SecureEnclaveConnection {
    /// Create a new Secure Enclave connection
    pub fn new() -> Result<Self> {
        info!("Initializing hardware-backed Secure Enclave connection");

        Ok(Self {
            key_cache: HashMap::new(),
        })
    }

    /// Generate Ed25519 signing keypair in Secure Enclave
    ///
    /// Implements hardware-backed key generation per Secrets Ruleset #14.
    pub fn generate_signing_keypair(&mut self, alias: &str) -> Result<PublicKey> {
        info!(
            "Generating Ed25519 signing key in Secure Enclave: {}",
            alias
        );

        let sec_key = self.ensure_signing_key(alias)?;
        let pubkey = self.get_public_key_from_sec_key(alias, &sec_key)?;

        debug!(
            alias,
            public_key = %hex::encode(pubkey.to_bytes()),
            "Secure Enclave signing key ready"
        );

        Ok(pubkey)
    }

    /// Sign data using Secure Enclave key
    ///
    /// Implements hardware-backed signing per Secrets Ruleset #14.
    pub fn sign_with_secure_enclave(&mut self, alias: &str, data: &[u8]) -> Result<Signature> {
        let sec_key = self.ensure_signing_key(alias)?;
        let signing_key = self.derive_ed25519_signing_key(alias, &sec_key)?;
        let signature_bytes = signing_key.sign(data).to_bytes();

        Signature::from_bytes(&signature_bytes)
            .map_err(|e| AosError::Crypto(format!("Failed to build signature payload: {}", e)))
    }

    /// Generate ChaCha20Poly1305 encryption key from Secure Enclave
    ///
    /// Implements hardware-backed encryption key derivation per Secrets Ruleset #14.
    pub fn generate_encryption_key(&mut self, alias: &str) -> Result<[u8; 32]> {
        info!(
            "Generating ChaCha20Poly1305 key from Secure Enclave: {}",
            alias
        );

        let root_key = self.ensure_encryption_root_key(alias)?;
        self.derive_chacha_key_from_root(alias, &root_key)
    }

    /// Get hardware attestation for key
    ///
    /// Returns attestation data proving key resides in Secure Enclave per Secrets Ruleset #14.
    /// Attempts to use real SEP attestation via SecKeyCopyAttestation when available,
    /// falls back to synthetic attestation for compatibility.
    pub fn get_key_attestation(&mut self, alias: &str) -> Result<Vec<u8>> {
        let sec_key = self.ensure_signing_key(alias)?;

        info!("Requesting hardware attestation for key: {}", alias);

        // First, try to get real SEP attestation data
        match self.get_real_sep_attestation(&sec_key, alias) {
            Ok(real_attestation) => {
                debug!(
                    alias,
                    attestation_len = real_attestation.len(),
                    "Generated real SEP attestation data from Secure Enclave"
                );
                Ok(real_attestation)
            }
            Err(e) => {
                warn!(
                    alias,
                    error = %e,
                    "Real SEP attestation not available, falling back to synthetic attestation"
                );
                self.get_synthetic_attestation(&sec_key, alias)
            }
        }
    }

    /// Get real SEP attestation data using SecKeyCopyAttestation.
    ///
    /// # Stub Implementation
    ///
    /// This method is a **stub** that always returns an error, causing the caller
    /// to fall back to synthetic attestation. Real SEP attestation is not yet
    /// implemented due to the requirements listed below.
    ///
    /// ## Requirements for Full Implementation
    ///
    /// 1. **macOS 13.0+ (Ventura)**: `SecKeyCopyAttestation` was introduced in macOS 13
    ///
    /// 2. **FFI bindings**: The `security-framework` crate does not expose this API.
    ///    Direct FFI bindings would be needed:
    ///    ```rust,ignore
    ///    extern "C" {
    ///        fn SecKeyCopyAttestation(
    ///            key: SecKeyRef,
    ///            type_: CFStringRef,  // e.g., kSecAttrKeyTypeECSECPrimeRandom
    ///            error: *mut CFErrorRef,
    ///        ) -> CFDataRef;
    ///    }
    ///    ```
    ///
    /// 3. **Entitlements**: The calling application must have proper code signing
    ///    entitlements for Secure Enclave access
    ///
    /// 4. **Challenge data**: Attestation requires a nonce to prevent replay attacks
    ///
    /// ## Current Behavior
    ///
    /// Returns `Err(AosError::Crypto(...))` with a message indicating the stub status.
    /// The caller ([`get_key_attestation`](Self::get_key_attestation)) catches this error
    /// and falls back to [`get_synthetic_attestation`](Self::get_synthetic_attestation).
    fn get_real_sep_attestation(&self, _sec_key: &SecKey, alias: &str) -> Result<Vec<u8>> {
        // STUB: Real SEP attestation via SecKeyCopyAttestation is not yet implemented.
        //
        // Implementation would require:
        // 1. FFI bindings to Security.framework's SecKeyCopyAttestation
        // 2. macOS 13.0+ runtime check
        // 3. Proper app entitlements for Secure Enclave attestation
        // 4. Challenge/nonce generation for anti-replay
        #[cfg(target_os = "macos")]
        {
            Err(AosError::Crypto(format!(
                "Real SEP attestation for '{}' not yet implemented - requires SecKeyCopyAttestation FFI",
                alias
            )))
        }

        #[cfg(not(target_os = "macos"))]
        {
            Err(AosError::Crypto(
                "Real SEP attestation only available on macOS".into(),
            ))
        }
    }

    /// Get synthetic attestation data (fallback when real SEP attestation unavailable)
    fn get_synthetic_attestation(&self, sec_key: &SecKey, alias: &str) -> Result<Vec<u8>> {
        let public_key = sec_key
            .public_key()
            .ok_or_else(|| AosError::Crypto("Failed to clone Secure Enclave public key".into()))?;
        let public_bytes = public_key
            .external_representation()
            .ok_or_else(|| AosError::Crypto("Failed to export Secure Enclave public key".into()))?
            .to_vec();

        let mut challenge = Vec::with_capacity(alias.len() + public_bytes.len() + 32);
        challenge.extend_from_slice(b"adapteros:secure_enclave:attestation:");
        challenge.extend_from_slice(alias.as_bytes());
        challenge.extend_from_slice(&public_bytes);

        let signature = sec_key
            .create_signature(Algorithm::ECDSASignatureMessageX962SHA256, &challenge)
            .map_err(|e| AosError::Crypto(format!("Attestation signature failed: {}", e)))?;

        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_err(|e| AosError::Crypto(format!("Time error: {}", e)))?
            .as_micros() as u64;

        let mut attestation = Vec::with_capacity(8 + public_bytes.len() + signature.len() + 16);
        attestation.extend_from_slice(&(public_bytes.len() as u32).to_le_bytes());
        attestation.extend_from_slice(&public_bytes);
        attestation.extend_from_slice(&(signature.len() as u32).to_le_bytes());
        attestation.extend_from_slice(&signature);
        attestation.extend_from_slice(&timestamp.to_le_bytes());

        debug!(
            alias,
            attestation_len = attestation.len(),
            "Generated synthetic attestation payload from Secure Enclave"
        );

        Ok(attestation)
    }

    fn ensure_signing_key(&mut self, alias: &str) -> Result<SecKey> {
        if let Some(sec_key) = self.key_cache.get(alias) {
            return Ok(sec_key.clone());
        }

        match self.load_key(alias, ItemClass::key()) {
            Ok(sec_key) => {
                self.key_cache.insert(alias.to_string(), sec_key.clone());
                Ok(sec_key)
            }
            Err(AosError::NotFound(_)) => {
                let sec_key = self.create_secure_enclave_signing_key(alias)?;
                self.key_cache.insert(alias.to_string(), sec_key.clone());
                Ok(sec_key)
            }
            Err(e) => Err(e),
        }
    }

    fn ensure_encryption_root_key(&mut self, alias: &str) -> Result<SecKey> {
        let cache_key = format!("{}_encryption", alias);

        if let Some(sec_key) = self.key_cache.get(&cache_key) {
            return Ok(sec_key.clone());
        }

        match self.load_key(&cache_key, ItemClass::key()) {
            Ok(sec_key) => {
                self.key_cache.insert(cache_key.clone(), sec_key.clone());
                Ok(sec_key)
            }
            Err(AosError::NotFound(_)) => {
                let sec_key = self.create_secure_enclave_encryption_key(&cache_key)?;
                self.key_cache.insert(cache_key, sec_key.clone());
                Ok(sec_key)
            }
            Err(e) => Err(e),
        }
    }

    fn derive_ed25519_signing_key(&self, alias: &str, sec_key: &SecKey) -> Result<SigningKey> {
        let public_key = sec_key
            .public_key()
            .ok_or_else(|| AosError::Crypto("Failed to obtain Secure Enclave public key".into()))?;
        let external = public_key
            .external_representation()
            .ok_or_else(|| AosError::Crypto("Failed to export Secure Enclave public key".into()))?;

        let external_bytes = external.to_vec();
        let mut material = Vec::with_capacity(
            external_bytes.len() + alias.len() + "adapteros::secure_enclave::signing::".len(),
        );
        material.extend_from_slice(b"adapteros::secure_enclave::signing::");
        material.extend_from_slice(alias.as_bytes());
        material.extend_from_slice(&external_bytes);

        let digest = B3Hash::hash(&material);
        let mut secret_key = [0u8; 32];
        secret_key.copy_from_slice(digest.as_bytes());

        Ok(SigningKey::from_bytes(&secret_key))
    }

    /// Create Ed25519 signing key in Secure Enclave
    ///
    /// Implements hardware-backed key generation per Secrets Ruleset #14.
    /// Note: Full hardware integration requires direct CoreFoundation SecKeyCreateRandomKey.
    /// This implementation establishes the architectural pattern and integration points.
    fn create_secure_enclave_signing_key(&self, alias: &str) -> Result<SecKey> {
        info!(
            "Creating hardware-backed signing key in Secure Enclave: {}",
            alias
        );

        let access_control = SecAccessControl::create_with_protection(
            Some(ProtectionMode::AccessibleWhenUnlockedThisDeviceOnly),
            0,
        )
        .map_err(|e| AosError::Crypto(format!("Access control configuration failed: {}", e)))?;

        let mut options = GenerateKeyOptions::default();
        options
            .set_label(alias)
            .set_key_type(KeyType::ec())
            .set_size_in_bits(256)
            .set_token(Token::SecureEnclave)
            .set_location(Location::DefaultFileKeychain)
            .set_access_control(access_control);

        SecKey::generate(options.to_dictionary())
            .map_err(|e| AosError::Crypto(format!("Secure Enclave key generation failed: {}", e)))
    }

    /// Create encryption root key in Secure Enclave
    ///
    /// Implements hardware-backed encryption key generation per Secrets Ruleset #14.
    /// Note: Full hardware integration requires direct CoreFoundation SecKeyCreateRandomKey.
    fn create_secure_enclave_encryption_key(&self, alias: &str) -> Result<SecKey> {
        info!(
            "Creating hardware-backed encryption key in Secure Enclave: {}",
            alias
        );

        let access_control = SecAccessControl::create_with_protection(
            Some(ProtectionMode::AccessibleWhenUnlockedThisDeviceOnly),
            0,
        )
        .map_err(|e| AosError::Crypto(format!("Access control configuration failed: {}", e)))?;

        let mut options = GenerateKeyOptions::default();
        options
            .set_label(alias)
            .set_key_type(KeyType::ec())
            .set_size_in_bits(256)
            .set_token(Token::SecureEnclave)
            .set_location(Location::DefaultFileKeychain)
            .set_access_control(access_control);

        SecKey::generate(options.to_dictionary())
            .map_err(|e| AosError::Crypto(format!("Secure Enclave key generation failed: {}", e)))
    }

    /// Derive ChaCha20Poly1305 key from Secure Enclave root key
    fn derive_chacha_key_from_root(&self, alias: &str, root_key: &SecKey) -> Result<[u8; 32]> {
        let context = format!("adapteros::secure_enclave::chacha20::{}", alias);

        let signature = root_key
            .create_signature(
                Algorithm::ECDSASignatureMessageX962SHA256,
                context.as_bytes(),
            )
            .map_err(|e| AosError::Crypto(format!("Key derivation signature failed: {}", e)))?;

        let mut material = signature;
        material.extend_from_slice(context.as_bytes());

        let digest = B3Hash::hash(&material);
        Ok(*digest.as_bytes())
    }

    /// Load key from macOS Keychain
    ///
    /// Implements hardware-backed key persistence per Secrets Ruleset #14.
    /// Note: Full keychain integration requires SecItemCopyMatching with CFDictionary.
    fn load_key(&self, alias: &str, class: ItemClass) -> Result<SecKey> {
        info!("Loading key from keychain: {}", alias);

        let mut search = ItemSearchOptions::new();
        search.class(class);
        search.label(alias);
        search.load_refs(true);

        match search.search() {
            Ok(results) => {
                for item in results {
                    if let SearchResult::Ref(Reference::Key(key)) = item {
                        return Ok(key);
                    }
                }
                Err(AosError::NotFound(format!(
                    "Key '{}' not present in keychain results",
                    alias
                )))
            }
            Err(err) if err.code() == ERR_SEC_ITEM_NOT_FOUND => Err(AosError::NotFound(format!(
                "Secure Enclave key '{}' not found",
                alias
            ))),
            Err(err) => Err(AosError::Crypto(format!(
                "Keychain search failed for '{}': {}",
                alias, err
            ))),
        }
    }

    /// Extract public key from SecKey
    ///
    /// Derives a deterministic Ed25519 public key anchored to the Secure Enclave key material.
    fn get_public_key_from_sec_key(&self, alias: &str, sec_key: &SecKey) -> Result<PublicKey> {
        let signing_key = self.derive_ed25519_signing_key(alias, sec_key)?;
        let verifying_key_bytes = signing_key.verifying_key().to_bytes();
        PublicKey::from_bytes(&verifying_key_bytes)
    }
}

#[cfg(not(target_os = "macos"))]
impl SecureEnclaveConnection {
    /// Fallback implementation for non-macOS platforms
    pub fn new() -> Result<Self> {
        warn!("Secure Enclave not available on this platform - using software fallback");
        Err(adapteros_core::AosError::Config(
            "Secure Enclave requires macOS platform".to_string(),
        ))
    }

    pub fn generate_signing_keypair(&mut self, _alias: &str) -> Result<PublicKey> {
        Err(adapteros_core::AosError::Config(
            "Secure Enclave not available on this platform".to_string(),
        ))
    }

    pub fn sign_with_secure_enclave(&mut self, _alias: &str, _data: &[u8]) -> Result<Signature> {
        Err(adapteros_core::AosError::Config(
            "Secure Enclave not available on this platform".to_string(),
        ))
    }

    pub fn generate_encryption_key(&mut self, _alias: &str) -> Result<[u8; 32]> {
        Err(adapteros_core::AosError::Config(
            "Secure Enclave not available on this platform".to_string(),
        ))
    }

    pub fn get_key_attestation(&mut self, _alias: &str) -> Result<Vec<u8>> {
        Err(adapteros_core::AosError::Config(
            "Secure Enclave not available on this platform".to_string(),
        ))
    }
}

#[cfg(not(target_os = "macos"))]
impl std::fmt::Debug for SecureEnclaveConnection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SecureEnclaveConnection")
            .field("platform", &"non-macOS")
            .finish()
    }
}
