import { defineConfig } from 'openapi-typescript';

/**
 * OpenAPI TypeScript Code Generation Configuration
 *
 * Converts AdapterOS OpenAPI specification to TypeScript types.
 * Generates zero-runtime-cost types for type-safe API interactions.
 *
 * Configuration Reference: https://openapi-ts.dev/
 */

export default defineConfig({
  // Input: OpenAPI specification file generated by Rust server
  // Location: target/codegen/openapi.json (generated by: cargo xtask codegen)
  input: '../target/codegen/openapi.json',

  // Output: TypeScript type definitions file
  // Location: ui/src/api/types.generated.ts (auto-imported in client)
  output: './src/api/types.generated.ts',

  // Type generation options
  exportType: true,        // Export all types as "export type" (not "export interface")
  enum: true,              // Generate enums from OpenAPI enum values
  enums: 'javascript',     // Use JavaScript objects for enums (not TypeScript enums)
  discriminators: true,    // Handle discriminator-based polymorphism
  defaultNonNullable: false, // Don't assume properties are non-null by default
  pathParamsAsTypes: true, // Generate types for path parameters

  // Additional configuration
  immutable: false,        // Allow mutable generated types
  prettify: true,          // Format output with Prettier (if available)

  // Transformation options (customize before generation)
  transform: {
    // Remove /api/v1 prefix from endpoint paths for cleaner types
    paths(path: string) {
      // Keep full paths - client.ts handles URL construction
      return path;
    },

    // Transform schema names if needed
    // schemaKeyTransform: (key) => key, // Keep default schema names
  },

  // Metadata comments in generated file
  comments: {
    enabled: true,
    style: 'block', // Block comments (/* ... */)
  },
});
