/**
 * OpenAPI TypeScript Code Generation Configuration
 *
 * Converts AdapterOS OpenAPI specification to TypeScript types.
 * Generates zero-runtime-cost types for type-safe API interactions.
 *
 * Configuration Reference: https://openapi-ts.dev/
 *
 * NOTE: openapi-typescript v7.x uses CLI flags, not config files.
 * This file documents the configuration for reference and future upgrades.
 * Current CLI command (see package.json):
 *   openapi-typescript ../target/codegen/openapi.json --output src/api/generated.ts
 *
 * To apply these settings, use CLI flags or update package.json script.
 */

/**
 * Configuration options for openapi-typescript v7.10.1
 *
 * Apply these via CLI flags:
 * --export-type            Export types (not values)
 * --enum                   Generate JavaScript enums for string enums
 * --alphabetize            Sort properties alphabetically
 * --empty-objects-unknown  Treat empty objects as unknown
 * --path-params-as-types   Use template literal types for path params
 */
const config = {
  // Input: OpenAPI specification file generated by Rust server
  // Location: ../target/codegen/openapi.json (generated by adapteros-server-api)
  input: '../target/codegen/openapi.json',

  // Output: TypeScript type definitions file
  // Location: ./src/api/generated.ts (matches package.json script)
  output: './src/api/generated.ts',

  // Export types (not values) - generates "export type" declarations
  // CLI: --export-type
  exportType: true,

  // Generate JavaScript enums for string enums defined in OpenAPI
  // CLI: --enum
  enum: true,

  // Treat empty objects as unknown (not {}) to prevent type pollution
  // CLI: --empty-objects-unknown
  emptyObjectsUnknown: true,

  // Don't assume properties are non-null by default (safer for optional fields)
  // CLI: --default-non-nullable=false
  defaultNonNullable: false,

  // Path parameters use template literal types for compile-time path validation
  // CLI: --path-params-as-types
  pathParamsAsTypes: true,

  // Allow mutable generated types (required for React state management)
  // CLI: (no flag needed, default is mutable)
  immutable: false,

  // Sort properties alphabetically for consistent diffs
  // CLI: --alphabetize
  alphabetize: true,
};

// Export default for compatibility with future versions that may support config files
export default config;
